/* tslint:disable */
/* eslint-disable */
/**
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d\'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L\'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d\'authentification de Yoxo 2. Demandez un jeton d\'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l\'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d\'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Skills d\'un joueur
 */
export interface SkillEntry {
    /**
     * Le pseudonyme du joueur
     */
    'username'?: string;
    /**
     * XP du joueur dans le métier de Builder. Paliers: Niveau 1: 5000 XP, Niveau 2: 20000 XP, Niveau 3: 50000 XP, Niveau 4: 100000 XP, Niveau 5: 200000 XP
     */
    'builder'?: number;
    /**
     * XP du joueur dans le métier d\'Agriculteur (Farmer). Paliers: Niveau 1: 5000 XP, Niveau 2: 20000 XP, Niveau 3: 60000 XP, Niveau 4: 125000 XP, Niveau 5: 300000 XP
     */
    'farmer'?: number;
    /**
     * XP du joueur dans le métier de Chasseur (Hunter). Paliers: Niveau 1: 5000 XP, Niveau 2: 20000 XP, Niveau 3: 50000 XP, Niveau 4: 100000 XP, Niveau 5: 200000 XP
     */
    'hunter'?: number;
    /**
     * XP du joueur dans le métier de Bûcheron (Lumberjack). Paliers: Niveau 1: 5000 XP, Niveau 2: 20000 XP, Niveau 3: 50000 XP, Niveau 4: 100000 XP, Niveau 5: 200000 XP
     */
    'lumberjack'?: number;
    /**
     * XP du joueur dans le métier d\'Ingénieur (Engineer). Paliers: Niveau 1: 3500 XP, Niveau 2: 15000 XP, Niveau 3: 30000 XP, Niveau 4: 70000 XP, Niveau 5: 200000 XP
     */
    'engineer'?: number;
    /**
     * XP du joueur dans le métier de Mineur (Miner). Paliers: Niveau 1: 5000 XP, Niveau 2: 20000 XP, Niveau 3: 75000 XP, Niveau 4: 150000 XP, Niveau 5: 400000 XP
     */
    'miner'?: number;
    /**
     * Position du joueur dans le classement serveur de le métier de Builder (1 = premier du classement)
     */
    'builderPosition'?: number;
    /**
     * Position du joueur dans le classement serveur de le métier d\'Agriculteur (1 = premier du classement)
     */
    'farmerPosition'?: number;
    /**
     * Position du joueur dans le classement serveur de le métier de Chasseur (1 = premier du classement)
     */
    'hunterPosition'?: number;
    /**
     * Position du joueur dans le classement serveur de le métier de Bûcheron (1 = premier du classement)
     */
    'lumberjackPosition'?: number;
    /**
     * Position du joueur dans le classement serveur de le métier d\'Ingénieur (1 = premier du classement)
     */
    'engineerPosition'?: number;
    /**
     * Position du joueur dans le classement serveur de le métier de Mineur (1 = premier du classement)
     */
    'minerPosition'?: number;
}

