# coding: utf-8

"""
    Yoxo API Server

    API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from yoxo_api_client.models.country_actions_entry import CountryActionsEntry
from yoxo_api_client.models.country_bank_entry import CountryBankEntry
from yoxo_api_client.models.country_coordinates import CountryCoordinates
from yoxo_api_client.models.country_settings_entry import CountrySettingsEntry
from yoxo_api_client.models.new_member_entry import NewMemberEntry
from yoxo_api_client.models.researches_entry import ResearchesEntry
from typing import Optional, Set
from typing_extensions import Self

class CountryEntry(BaseModel):
    """
    Données d'un pays
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Nom du pays")
    description: Optional[StrictStr] = Field(default=None, description="Description du pays")
    motd: Optional[StrictStr] = Field(default=None, description="Message du jour (MOTD)")
    entry_msg: Optional[StrictStr] = Field(default=None, description="Message d'entrée sur le territoire", alias="entryMsg")
    age: Optional[StrictInt] = Field(default=None, description="Âge du pays en jours")
    count_members: Optional[StrictInt] = Field(default=None, description="Nombre de membres", alias="countMembers")
    count_new_members: Optional[StrictInt] = Field(default=None, description="Nombre de nouvelles recrues", alias="countNewMembers")
    fhome_coord: Optional[CountryCoordinates] = Field(default=None, alias="fhomeCoord")
    level: Optional[StrictInt] = Field(default=None, description="Niveau du pays")
    progress: Optional[StrictInt] = Field(default=None, description="Progression vers le niveau suivant (en pourcentage)")
    notations_position: Optional[StrictInt] = Field(default=None, description="Position dans le classement des notations", alias="notationsPosition")
    tags: Optional[List[StrictStr]] = Field(default=None, description="Tags du pays")
    discord: Optional[StrictStr] = Field(default=None, description="Lien discord")
    alliance_name: Optional[StrictStr] = Field(default=None, description="Nom de l'alliance", alias="allianceName")
    mmr: Optional[StrictInt] = Field(default=None, description="Score MMR")
    claims: Optional[StrictInt] = Field(default=None, description="Nombre de chunks claim")
    power: Optional[StrictInt] = Field(default=None, description="Power actuel")
    max_power: Optional[StrictInt] = Field(default=None, description="Power maximum", alias="maxPower")
    powerboost_fixed: Optional[StrictInt] = Field(default=None, description="Power boost fixe", alias="powerboostFixed")
    powerboost_warzone: Optional[StrictInt] = Field(default=None, description="Power boost warzone", alias="powerboostWarzone")
    powerboost_unesco: Optional[StrictInt] = Field(default=None, description="Power boost UNESCO", alias="powerboostUnesco")
    powerboost_new_member: Optional[StrictInt] = Field(default=None, description="Power boost obtenu via les nouveaux membres", alias="powerboostNewMember")
    powerboost_malus_assault: Optional[StrictInt] = Field(default=None, description="Malus de power lié aux assauts", alias="powerboostMalusAssault")
    flag: Optional[StrictStr] = Field(default=None, description="Drapeau (en base64)")
    leader: Optional[StrictStr] = Field(default=None, description="Chef du pays")
    officers: Optional[List[StrictStr]] = Field(default=None, description="Officiers")
    members: Optional[List[StrictStr]] = Field(default=None, description="Membres")
    recruits: Optional[List[StrictStr]] = Field(default=None, description="Recrues")
    new_members: Optional[List[NewMemberEntry]] = Field(default=None, description="Informations détaillé sur les nouvelles recrues", alias="newMembers")
    researches_level: Optional[ResearchesEntry] = Field(default=None, alias="researchesLevel")
    wars: Optional[List[StrictStr]] = Field(default=None, description="Guerres en cours")
    bank: Optional[CountryBankEntry] = None
    actions: Optional[CountryActionsEntry] = None
    settings: Optional[CountrySettingsEntry] = None
    top_warzone: Optional[StrictBool] = Field(default=None, alias="topWarzone")
    restrict_assault: Optional[StrictBool] = Field(default=None, alias="restrictAssault")
    restrict_missile: Optional[StrictBool] = Field(default=None, alias="restrictMissile")
    empire: Optional[StrictBool] = None
    referent: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["name", "description", "motd", "entryMsg", "age", "countMembers", "countNewMembers", "fhomeCoord", "level", "progress", "notationsPosition", "tags", "discord", "allianceName", "mmr", "claims", "power", "maxPower", "powerboostFixed", "powerboostWarzone", "powerboostUnesco", "powerboostNewMember", "powerboostMalusAssault", "flag", "leader", "officers", "members", "recruits", "newMembers", "researchesLevel", "wars", "bank", "actions", "settings", "topWarzone", "restrictAssault", "restrictMissile", "empire", "referent"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CountryEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of fhome_coord
        if self.fhome_coord:
            _dict['fhomeCoord'] = self.fhome_coord.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in new_members (list)
        _items = []
        if self.new_members:
            for _item_new_members in self.new_members:
                if _item_new_members:
                    _items.append(_item_new_members.to_dict())
            _dict['newMembers'] = _items
        # override the default output from pydantic by calling `to_dict()` of researches_level
        if self.researches_level:
            _dict['researchesLevel'] = self.researches_level.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bank
        if self.bank:
            _dict['bank'] = self.bank.to_dict()
        # override the default output from pydantic by calling `to_dict()` of actions
        if self.actions:
            _dict['actions'] = self.actions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of settings
        if self.settings:
            _dict['settings'] = self.settings.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CountryEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "motd": obj.get("motd"),
            "entryMsg": obj.get("entryMsg"),
            "age": obj.get("age"),
            "countMembers": obj.get("countMembers"),
            "countNewMembers": obj.get("countNewMembers"),
            "fhomeCoord": CountryCoordinates.from_dict(obj["fhomeCoord"]) if obj.get("fhomeCoord") is not None else None,
            "level": obj.get("level"),
            "progress": obj.get("progress"),
            "notationsPosition": obj.get("notationsPosition"),
            "tags": obj.get("tags"),
            "discord": obj.get("discord"),
            "allianceName": obj.get("allianceName"),
            "mmr": obj.get("mmr"),
            "claims": obj.get("claims"),
            "power": obj.get("power"),
            "maxPower": obj.get("maxPower"),
            "powerboostFixed": obj.get("powerboostFixed"),
            "powerboostWarzone": obj.get("powerboostWarzone"),
            "powerboostUnesco": obj.get("powerboostUnesco"),
            "powerboostNewMember": obj.get("powerboostNewMember"),
            "powerboostMalusAssault": obj.get("powerboostMalusAssault"),
            "flag": obj.get("flag"),
            "leader": obj.get("leader"),
            "officers": obj.get("officers"),
            "members": obj.get("members"),
            "recruits": obj.get("recruits"),
            "newMembers": [NewMemberEntry.from_dict(_item) for _item in obj["newMembers"]] if obj.get("newMembers") is not None else None,
            "researchesLevel": ResearchesEntry.from_dict(obj["researchesLevel"]) if obj.get("researchesLevel") is not None else None,
            "wars": obj.get("wars"),
            "bank": CountryBankEntry.from_dict(obj["bank"]) if obj.get("bank") is not None else None,
            "actions": CountryActionsEntry.from_dict(obj["actions"]) if obj.get("actions") is not None else None,
            "settings": CountrySettingsEntry.from_dict(obj["settings"]) if obj.get("settings") is not None else None,
            "topWarzone": obj.get("topWarzone"),
            "restrictAssault": obj.get("restrictAssault"),
            "restrictMissile": obj.get("restrictMissile"),
            "empire": obj.get("empire"),
            "referent": obj.get("referent")
        })
        return _obj


