/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * Banque de l&#39;alliance
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class AllianceBank {
  public static final String SERIALIZED_NAME_CURRENT_ACCOUNT_BALANCE = "currentAccountBalance";
  @SerializedName(SERIALIZED_NAME_CURRENT_ACCOUNT_BALANCE)
  @javax.annotation.Nullable
  private Double currentAccountBalance;

  public static final String SERIALIZED_NAME_BLOCKED_ACCOUNT_BALANCE = "blockedAccountBalance";
  @SerializedName(SERIALIZED_NAME_BLOCKED_ACCOUNT_BALANCE)
  @javax.annotation.Nullable
  private Double blockedAccountBalance;

  public AllianceBank() {
  }

  public AllianceBank currentAccountBalance(@javax.annotation.Nullable Double currentAccountBalance) {
    this.currentAccountBalance = currentAccountBalance;
    return this;
  }

  /**
   * L&#39;argent sur le compte courant de l&#39;alliance
   * @return currentAccountBalance
   */
  @javax.annotation.Nullable
  public Double getCurrentAccountBalance() {
    return currentAccountBalance;
  }

  public void setCurrentAccountBalance(@javax.annotation.Nullable Double currentAccountBalance) {
    this.currentAccountBalance = currentAccountBalance;
  }


  public AllianceBank blockedAccountBalance(@javax.annotation.Nullable Double blockedAccountBalance) {
    this.blockedAccountBalance = blockedAccountBalance;
    return this;
  }

  /**
   * L&#39;argent sur le compte bloqué de l&#39;alliance
   * @return blockedAccountBalance
   */
  @javax.annotation.Nullable
  public Double getBlockedAccountBalance() {
    return blockedAccountBalance;
  }

  public void setBlockedAccountBalance(@javax.annotation.Nullable Double blockedAccountBalance) {
    this.blockedAccountBalance = blockedAccountBalance;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllianceBank allianceBank = (AllianceBank) o;
    return Objects.equals(this.currentAccountBalance, allianceBank.currentAccountBalance) &&
        Objects.equals(this.blockedAccountBalance, allianceBank.blockedAccountBalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentAccountBalance, blockedAccountBalance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllianceBank {\n");
    sb.append("    currentAccountBalance: ").append(toIndentedString(currentAccountBalance)).append("\n");
    sb.append("    blockedAccountBalance: ").append(toIndentedString(blockedAccountBalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("currentAccountBalance", "blockedAccountBalance"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AllianceBank
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AllianceBank.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AllianceBank is not found in the empty JSON string", AllianceBank.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AllianceBank.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AllianceBank` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AllianceBank.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AllianceBank' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AllianceBank> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AllianceBank.class));

       return (TypeAdapter<T>) new TypeAdapter<AllianceBank>() {
           @Override
           public void write(JsonWriter out, AllianceBank value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AllianceBank read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AllianceBank given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AllianceBank
   * @throws IOException if the JSON string is invalid with respect to AllianceBank
   */
  public static AllianceBank fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AllianceBank.class);
  }

  /**
   * Convert an instance of AllianceBank to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

