/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import software.yoxo.client.model.AllianceBank;
import software.yoxo.client.model.AllianceModule;
import software.yoxo.client.model.AlliancePrimeBoost;
import software.yoxo.client.model.AllianceRelation;
import software.yoxo.client.model.AllianceTaxes;
import software.yoxo.client.model.AllianceVoteHistory;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * Données d&#39;une alliance
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class AllianceEntry {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private Long createdAt;

  public static final String SERIALIZED_NAME_COLOR = "color";
  @SerializedName(SERIALIZED_NAME_COLOR)
  @javax.annotation.Nullable
  private String color;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_DISCORD = "discord";
  @SerializedName(SERIALIZED_NAME_DISCORD)
  @javax.annotation.Nullable
  private String discord;

  public static final String SERIALIZED_NAME_YOUTUBE = "youtube";
  @SerializedName(SERIALIZED_NAME_YOUTUBE)
  @javax.annotation.Nullable
  private String youtube;

  public static final String SERIALIZED_NAME_RULES = "rules";
  @SerializedName(SERIALIZED_NAME_RULES)
  @javax.annotation.Nullable
  private String rules;

  public static final String SERIALIZED_NAME_BANNER_URL = "bannerUrl";
  @SerializedName(SERIALIZED_NAME_BANNER_URL)
  @javax.annotation.Nullable
  private String bannerUrl;

  public static final String SERIALIZED_NAME_BLAZON = "blazon";
  @SerializedName(SERIALIZED_NAME_BLAZON)
  @javax.annotation.Nullable
  private String blazon;

  public static final String SERIALIZED_NAME_RANKING = "ranking";
  @SerializedName(SERIALIZED_NAME_RANKING)
  @javax.annotation.Nullable
  private Integer ranking;

  public static final String SERIALIZED_NAME_PRESTIGE_POINTS = "prestigePoints";
  @SerializedName(SERIALIZED_NAME_PRESTIGE_POINTS)
  @javax.annotation.Nullable
  private Integer prestigePoints;

  public static final String SERIALIZED_NAME_STATION_MODULE_COUNT = "stationModuleCount";
  @SerializedName(SERIALIZED_NAME_STATION_MODULE_COUNT)
  @javax.annotation.Nullable
  private Integer stationModuleCount;

  public static final String SERIALIZED_NAME_COUNTRY_COUNT = "countryCount";
  @SerializedName(SERIALIZED_NAME_COUNTRY_COUNT)
  @javax.annotation.Nullable
  private Integer countryCount;

  public static final String SERIALIZED_NAME_LEADERS = "leaders";
  @SerializedName(SERIALIZED_NAME_LEADERS)
  @javax.annotation.Nullable
  private List<String> leaders = new ArrayList<>();

  public static final String SERIALIZED_NAME_MEMBERS = "members";
  @SerializedName(SERIALIZED_NAME_MEMBERS)
  @javax.annotation.Nullable
  private List<String> members = new ArrayList<>();

  public static final String SERIALIZED_NAME_PROTECTORATS = "protectorats";
  @SerializedName(SERIALIZED_NAME_PROTECTORATS)
  @javax.annotation.Nullable
  private List<String> protectorats = new ArrayList<>();

  public static final String SERIALIZED_NAME_CLAIMS = "claims";
  @SerializedName(SERIALIZED_NAME_CLAIMS)
  @javax.annotation.Nullable
  private Integer claims;

  public static final String SERIALIZED_NAME_COUNT_MEMBERS = "countMembers";
  @SerializedName(SERIALIZED_NAME_COUNT_MEMBERS)
  @javax.annotation.Nullable
  private Integer countMembers;

  public static final String SERIALIZED_NAME_TAXES = "taxes";
  @SerializedName(SERIALIZED_NAME_TAXES)
  @javax.annotation.Nullable
  private AllianceTaxes taxes;

  public static final String SERIALIZED_NAME_MODULES = "modules";
  @SerializedName(SERIALIZED_NAME_MODULES)
  @javax.annotation.Nullable
  private List<AllianceModule> modules = new ArrayList<>();

  public static final String SERIALIZED_NAME_BANK = "bank";
  @SerializedName(SERIALIZED_NAME_BANK)
  @javax.annotation.Nullable
  private AllianceBank bank;

  public static final String SERIALIZED_NAME_VOTES_HISTORY = "votesHistory";
  @SerializedName(SERIALIZED_NAME_VOTES_HISTORY)
  @javax.annotation.Nullable
  private List<AllianceVoteHistory> votesHistory = new ArrayList<>();

  public static final String SERIALIZED_NAME_RELATIONS = "relations";
  @SerializedName(SERIALIZED_NAME_RELATIONS)
  @javax.annotation.Nullable
  private List<AllianceRelation> relations = new ArrayList<>();

  public static final String SERIALIZED_NAME_PRIME_BOOST = "primeBoost";
  @SerializedName(SERIALIZED_NAME_PRIME_BOOST)
  @javax.annotation.Nullable
  private AlliancePrimeBoost primeBoost;

  public static final String SERIALIZED_NAME_OPEN = "open";
  @SerializedName(SERIALIZED_NAME_OPEN)
  @javax.annotation.Nullable
  private Boolean open;

  public AllianceEntry() {
  }

  public AllianceEntry name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Le nom de l&#39;alliance
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public AllianceEntry description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * La description de l&#39;alliance
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public AllianceEntry createdAt(@javax.annotation.Nullable Long createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Le timestamp en ms à la date dont l&#39;alliance a été créer
   * @return createdAt
   */
  @javax.annotation.Nullable
  public Long getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable Long createdAt) {
    this.createdAt = createdAt;
  }


  public AllianceEntry color(@javax.annotation.Nullable String color) {
    this.color = color;
    return this;
  }

  /**
   * La couleur de l&#39;alliance au format héxadécimale. La couleur représente l&#39;alliance et est unique à l&#39;échelle du serveur
   * @return color
   */
  @javax.annotation.Nullable
  public String getColor() {
    return color;
  }

  public void setColor(@javax.annotation.Nullable String color) {
    this.color = color;
  }


  public AllianceEntry tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public AllianceEntry addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * La liste des tags de l&#39;alliance
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }


  public AllianceEntry discord(@javax.annotation.Nullable String discord) {
    this.discord = discord;
    return this;
  }

  /**
   * Le lien menant au discord de l&#39;alliance
   * @return discord
   */
  @javax.annotation.Nullable
  public String getDiscord() {
    return discord;
  }

  public void setDiscord(@javax.annotation.Nullable String discord) {
    this.discord = discord;
  }


  public AllianceEntry youtube(@javax.annotation.Nullable String youtube) {
    this.youtube = youtube;
    return this;
  }

  /**
   * Le lien menant à la chaine youtube de l&#39;alliance
   * @return youtube
   */
  @javax.annotation.Nullable
  public String getYoutube() {
    return youtube;
  }

  public void setYoutube(@javax.annotation.Nullable String youtube) {
    this.youtube = youtube;
  }


  public AllianceEntry rules(@javax.annotation.Nullable String rules) {
    this.rules = rules;
    return this;
  }

  /**
   * Les règles de l&#39;alliance
   * @return rules
   */
  @javax.annotation.Nullable
  public String getRules() {
    return rules;
  }

  public void setRules(@javax.annotation.Nullable String rules) {
    this.rules = rules;
  }


  public AllianceEntry bannerUrl(@javax.annotation.Nullable String bannerUrl) {
    this.bannerUrl = bannerUrl;
    return this;
  }

  /**
   * L&#39;url de la banière affiché sur la page de l&#39;alliance
   * @return bannerUrl
   */
  @javax.annotation.Nullable
  public String getBannerUrl() {
    return bannerUrl;
  }

  public void setBannerUrl(@javax.annotation.Nullable String bannerUrl) {
    this.bannerUrl = bannerUrl;
  }


  public AllianceEntry blazon(@javax.annotation.Nullable String blazon) {
    this.blazon = blazon;
    return this;
  }

  /**
   * Le blazon représentant l&#39;alliance. Image en base64, de dimension 78x78
   * @return blazon
   */
  @javax.annotation.Nullable
  public String getBlazon() {
    return blazon;
  }

  public void setBlazon(@javax.annotation.Nullable String blazon) {
    this.blazon = blazon;
  }


  public AllianceEntry ranking(@javax.annotation.Nullable Integer ranking) {
    this.ranking = ranking;
    return this;
  }

  /**
   * Le classement de l&#39;alliance sur le mois en cours. Calculé en fonction du nombre de points de prestiges
   * @return ranking
   */
  @javax.annotation.Nullable
  public Integer getRanking() {
    return ranking;
  }

  public void setRanking(@javax.annotation.Nullable Integer ranking) {
    this.ranking = ranking;
  }


  public AllianceEntry prestigePoints(@javax.annotation.Nullable Integer prestigePoints) {
    this.prestigePoints = prestigePoints;
    return this;
  }

  /**
   * Les points de prestige de l&#39;alliance. La documentation du prestige est consultable à l&#39;adresse https://wiki.nationsglory.fr/fr/article/les-alliances-java-1ju6vju/#1-prestige-classement
   * @return prestigePoints
   */
  @javax.annotation.Nullable
  public Integer getPrestigePoints() {
    return prestigePoints;
  }

  public void setPrestigePoints(@javax.annotation.Nullable Integer prestigePoints) {
    this.prestigePoints = prestigePoints;
  }


  public AllianceEntry stationModuleCount(@javax.annotation.Nullable Integer stationModuleCount) {
    this.stationModuleCount = stationModuleCount;
    return this;
  }

  /**
   * Le nombre de module dans la station spatiale de l&#39;alliance
   * @return stationModuleCount
   */
  @javax.annotation.Nullable
  public Integer getStationModuleCount() {
    return stationModuleCount;
  }

  public void setStationModuleCount(@javax.annotation.Nullable Integer stationModuleCount) {
    this.stationModuleCount = stationModuleCount;
  }


  public AllianceEntry countryCount(@javax.annotation.Nullable Integer countryCount) {
    this.countryCount = countryCount;
    return this;
  }

  /**
   * Le nombre de pays dans l&#39;alliance
   * @return countryCount
   */
  @javax.annotation.Nullable
  public Integer getCountryCount() {
    return countryCount;
  }

  public void setCountryCount(@javax.annotation.Nullable Integer countryCount) {
    this.countryCount = countryCount;
  }


  public AllianceEntry leaders(@javax.annotation.Nullable List<String> leaders) {
    this.leaders = leaders;
    return this;
  }

  public AllianceEntry addLeadersItem(String leadersItem) {
    if (this.leaders == null) {
      this.leaders = new ArrayList<>();
    }
    this.leaders.add(leadersItem);
    return this;
  }

  /**
   * La liste des pays leader de l&#39;alliance
   * @return leaders
   */
  @javax.annotation.Nullable
  public List<String> getLeaders() {
    return leaders;
  }

  public void setLeaders(@javax.annotation.Nullable List<String> leaders) {
    this.leaders = leaders;
  }


  public AllianceEntry members(@javax.annotation.Nullable List<String> members) {
    this.members = members;
    return this;
  }

  public AllianceEntry addMembersItem(String membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

  /**
   * La liste des pays membres de l&#39;alliance
   * @return members
   */
  @javax.annotation.Nullable
  public List<String> getMembers() {
    return members;
  }

  public void setMembers(@javax.annotation.Nullable List<String> members) {
    this.members = members;
  }


  public AllianceEntry protectorats(@javax.annotation.Nullable List<String> protectorats) {
    this.protectorats = protectorats;
    return this;
  }

  public AllianceEntry addProtectoratsItem(String protectoratsItem) {
    if (this.protectorats == null) {
      this.protectorats = new ArrayList<>();
    }
    this.protectorats.add(protectoratsItem);
    return this;
  }

  /**
   * La liste des pays sous le statut de protectorat dans l&#39;alliance
   * @return protectorats
   */
  @javax.annotation.Nullable
  public List<String> getProtectorats() {
    return protectorats;
  }

  public void setProtectorats(@javax.annotation.Nullable List<String> protectorats) {
    this.protectorats = protectorats;
  }


  public AllianceEntry claims(@javax.annotation.Nullable Integer claims) {
    this.claims = claims;
    return this;
  }

  /**
   * Le nombre de claims cumulé des pays de l&#39;alliance
   * @return claims
   */
  @javax.annotation.Nullable
  public Integer getClaims() {
    return claims;
  }

  public void setClaims(@javax.annotation.Nullable Integer claims) {
    this.claims = claims;
  }


  public AllianceEntry countMembers(@javax.annotation.Nullable Integer countMembers) {
    this.countMembers = countMembers;
    return this;
  }

  /**
   * Le nombre de membres cumulés des pays de l&#39;alliance
   * @return countMembers
   */
  @javax.annotation.Nullable
  public Integer getCountMembers() {
    return countMembers;
  }

  public void setCountMembers(@javax.annotation.Nullable Integer countMembers) {
    this.countMembers = countMembers;
  }


  public AllianceEntry taxes(@javax.annotation.Nullable AllianceTaxes taxes) {
    this.taxes = taxes;
    return this;
  }

  /**
   * Get taxes
   * @return taxes
   */
  @javax.annotation.Nullable
  public AllianceTaxes getTaxes() {
    return taxes;
  }

  public void setTaxes(@javax.annotation.Nullable AllianceTaxes taxes) {
    this.taxes = taxes;
  }


  public AllianceEntry modules(@javax.annotation.Nullable List<AllianceModule> modules) {
    this.modules = modules;
    return this;
  }

  public AllianceEntry addModulesItem(AllianceModule modulesItem) {
    if (this.modules == null) {
      this.modules = new ArrayList<>();
    }
    this.modules.add(modulesItem);
    return this;
  }

  /**
   * Les modules construits dans la station spatiale
   * @return modules
   */
  @javax.annotation.Nullable
  public List<AllianceModule> getModules() {
    return modules;
  }

  public void setModules(@javax.annotation.Nullable List<AllianceModule> modules) {
    this.modules = modules;
  }


  public AllianceEntry bank(@javax.annotation.Nullable AllianceBank bank) {
    this.bank = bank;
    return this;
  }

  /**
   * Get bank
   * @return bank
   */
  @javax.annotation.Nullable
  public AllianceBank getBank() {
    return bank;
  }

  public void setBank(@javax.annotation.Nullable AllianceBank bank) {
    this.bank = bank;
  }


  public AllianceEntry votesHistory(@javax.annotation.Nullable List<AllianceVoteHistory> votesHistory) {
    this.votesHistory = votesHistory;
    return this;
  }

  public AllianceEntry addVotesHistoryItem(AllianceVoteHistory votesHistoryItem) {
    if (this.votesHistory == null) {
      this.votesHistory = new ArrayList<>();
    }
    this.votesHistory.add(votesHistoryItem);
    return this;
  }

  /**
   * L&#39;historique des votes de l&#39;alliance. Nécessite d&#39;être membre de l&#39;alliance pour y avoir accès
   * @return votesHistory
   */
  @javax.annotation.Nullable
  public List<AllianceVoteHistory> getVotesHistory() {
    return votesHistory;
  }

  public void setVotesHistory(@javax.annotation.Nullable List<AllianceVoteHistory> votesHistory) {
    this.votesHistory = votesHistory;
  }


  public AllianceEntry relations(@javax.annotation.Nullable List<AllianceRelation> relations) {
    this.relations = relations;
    return this;
  }

  public AllianceEntry addRelationsItem(AllianceRelation relationsItem) {
    if (this.relations == null) {
      this.relations = new ArrayList<>();
    }
    this.relations.add(relationsItem);
    return this;
  }

  /**
   * Les relations avec les autres alliances
   * @return relations
   */
  @javax.annotation.Nullable
  public List<AllianceRelation> getRelations() {
    return relations;
  }

  public void setRelations(@javax.annotation.Nullable List<AllianceRelation> relations) {
    this.relations = relations;
  }


  public AllianceEntry primeBoost(@javax.annotation.Nullable AlliancePrimeBoost primeBoost) {
    this.primeBoost = primeBoost;
    return this;
  }

  /**
   * Get primeBoost
   * @return primeBoost
   */
  @javax.annotation.Nullable
  public AlliancePrimeBoost getPrimeBoost() {
    return primeBoost;
  }

  public void setPrimeBoost(@javax.annotation.Nullable AlliancePrimeBoost primeBoost) {
    this.primeBoost = primeBoost;
  }


  public AllianceEntry open(@javax.annotation.Nullable Boolean open) {
    this.open = open;
    return this;
  }

  /**
   * Get open
   * @return open
   */
  @javax.annotation.Nullable
  public Boolean getOpen() {
    return open;
  }

  public void setOpen(@javax.annotation.Nullable Boolean open) {
    this.open = open;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllianceEntry allianceEntry = (AllianceEntry) o;
    return Objects.equals(this.name, allianceEntry.name) &&
        Objects.equals(this.description, allianceEntry.description) &&
        Objects.equals(this.createdAt, allianceEntry.createdAt) &&
        Objects.equals(this.color, allianceEntry.color) &&
        Objects.equals(this.tags, allianceEntry.tags) &&
        Objects.equals(this.discord, allianceEntry.discord) &&
        Objects.equals(this.youtube, allianceEntry.youtube) &&
        Objects.equals(this.rules, allianceEntry.rules) &&
        Objects.equals(this.bannerUrl, allianceEntry.bannerUrl) &&
        Objects.equals(this.blazon, allianceEntry.blazon) &&
        Objects.equals(this.ranking, allianceEntry.ranking) &&
        Objects.equals(this.prestigePoints, allianceEntry.prestigePoints) &&
        Objects.equals(this.stationModuleCount, allianceEntry.stationModuleCount) &&
        Objects.equals(this.countryCount, allianceEntry.countryCount) &&
        Objects.equals(this.leaders, allianceEntry.leaders) &&
        Objects.equals(this.members, allianceEntry.members) &&
        Objects.equals(this.protectorats, allianceEntry.protectorats) &&
        Objects.equals(this.claims, allianceEntry.claims) &&
        Objects.equals(this.countMembers, allianceEntry.countMembers) &&
        Objects.equals(this.taxes, allianceEntry.taxes) &&
        Objects.equals(this.modules, allianceEntry.modules) &&
        Objects.equals(this.bank, allianceEntry.bank) &&
        Objects.equals(this.votesHistory, allianceEntry.votesHistory) &&
        Objects.equals(this.relations, allianceEntry.relations) &&
        Objects.equals(this.primeBoost, allianceEntry.primeBoost) &&
        Objects.equals(this.open, allianceEntry.open);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, createdAt, color, tags, discord, youtube, rules, bannerUrl, blazon, ranking, prestigePoints, stationModuleCount, countryCount, leaders, members, protectorats, claims, countMembers, taxes, modules, bank, votesHistory, relations, primeBoost, open);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllianceEntry {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    discord: ").append(toIndentedString(discord)).append("\n");
    sb.append("    youtube: ").append(toIndentedString(youtube)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    bannerUrl: ").append(toIndentedString(bannerUrl)).append("\n");
    sb.append("    blazon: ").append(toIndentedString(blazon)).append("\n");
    sb.append("    ranking: ").append(toIndentedString(ranking)).append("\n");
    sb.append("    prestigePoints: ").append(toIndentedString(prestigePoints)).append("\n");
    sb.append("    stationModuleCount: ").append(toIndentedString(stationModuleCount)).append("\n");
    sb.append("    countryCount: ").append(toIndentedString(countryCount)).append("\n");
    sb.append("    leaders: ").append(toIndentedString(leaders)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    protectorats: ").append(toIndentedString(protectorats)).append("\n");
    sb.append("    claims: ").append(toIndentedString(claims)).append("\n");
    sb.append("    countMembers: ").append(toIndentedString(countMembers)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("    modules: ").append(toIndentedString(modules)).append("\n");
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("    votesHistory: ").append(toIndentedString(votesHistory)).append("\n");
    sb.append("    relations: ").append(toIndentedString(relations)).append("\n");
    sb.append("    primeBoost: ").append(toIndentedString(primeBoost)).append("\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "description", "createdAt", "color", "tags", "discord", "youtube", "rules", "bannerUrl", "blazon", "ranking", "prestigePoints", "stationModuleCount", "countryCount", "leaders", "members", "protectorats", "claims", "countMembers", "taxes", "modules", "bank", "votesHistory", "relations", "primeBoost", "open"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AllianceEntry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AllianceEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AllianceEntry is not found in the empty JSON string", AllianceEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AllianceEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AllianceEntry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("color") != null && !jsonObj.get("color").isJsonNull()) && !jsonObj.get("color").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `color` to be a primitive type in the JSON string but got `%s`", jsonObj.get("color").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
      if ((jsonObj.get("discord") != null && !jsonObj.get("discord").isJsonNull()) && !jsonObj.get("discord").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `discord` to be a primitive type in the JSON string but got `%s`", jsonObj.get("discord").toString()));
      }
      if ((jsonObj.get("youtube") != null && !jsonObj.get("youtube").isJsonNull()) && !jsonObj.get("youtube").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `youtube` to be a primitive type in the JSON string but got `%s`", jsonObj.get("youtube").toString()));
      }
      if ((jsonObj.get("rules") != null && !jsonObj.get("rules").isJsonNull()) && !jsonObj.get("rules").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `rules` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rules").toString()));
      }
      if ((jsonObj.get("bannerUrl") != null && !jsonObj.get("bannerUrl").isJsonNull()) && !jsonObj.get("bannerUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `bannerUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bannerUrl").toString()));
      }
      if ((jsonObj.get("blazon") != null && !jsonObj.get("blazon").isJsonNull()) && !jsonObj.get("blazon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `blazon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("blazon").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("leaders") != null && !jsonObj.get("leaders").isJsonNull() && !jsonObj.get("leaders").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `leaders` to be an array in the JSON string but got `%s`", jsonObj.get("leaders").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("members") != null && !jsonObj.get("members").isJsonNull() && !jsonObj.get("members").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `members` to be an array in the JSON string but got `%s`", jsonObj.get("members").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("protectorats") != null && !jsonObj.get("protectorats").isJsonNull() && !jsonObj.get("protectorats").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `protectorats` to be an array in the JSON string but got `%s`", jsonObj.get("protectorats").toString()));
      }
      // validate the optional field `taxes`
      if (jsonObj.get("taxes") != null && !jsonObj.get("taxes").isJsonNull()) {
        AllianceTaxes.validateJsonElement(jsonObj.get("taxes"));
      }
      if (jsonObj.get("modules") != null && !jsonObj.get("modules").isJsonNull()) {
        JsonArray jsonArraymodules = jsonObj.getAsJsonArray("modules");
        if (jsonArraymodules != null) {
          // ensure the json data is an array
          if (!jsonObj.get("modules").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `modules` to be an array in the JSON string but got `%s`", jsonObj.get("modules").toString()));
          }

          // validate the optional field `modules` (array)
          for (int i = 0; i < jsonArraymodules.size(); i++) {
            AllianceModule.validateJsonElement(jsonArraymodules.get(i));
          };
        }
      }
      // validate the optional field `bank`
      if (jsonObj.get("bank") != null && !jsonObj.get("bank").isJsonNull()) {
        AllianceBank.validateJsonElement(jsonObj.get("bank"));
      }
      if (jsonObj.get("votesHistory") != null && !jsonObj.get("votesHistory").isJsonNull()) {
        JsonArray jsonArrayvotesHistory = jsonObj.getAsJsonArray("votesHistory");
        if (jsonArrayvotesHistory != null) {
          // ensure the json data is an array
          if (!jsonObj.get("votesHistory").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `votesHistory` to be an array in the JSON string but got `%s`", jsonObj.get("votesHistory").toString()));
          }

          // validate the optional field `votesHistory` (array)
          for (int i = 0; i < jsonArrayvotesHistory.size(); i++) {
            AllianceVoteHistory.validateJsonElement(jsonArrayvotesHistory.get(i));
          };
        }
      }
      if (jsonObj.get("relations") != null && !jsonObj.get("relations").isJsonNull()) {
        JsonArray jsonArrayrelations = jsonObj.getAsJsonArray("relations");
        if (jsonArrayrelations != null) {
          // ensure the json data is an array
          if (!jsonObj.get("relations").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `relations` to be an array in the JSON string but got `%s`", jsonObj.get("relations").toString()));
          }

          // validate the optional field `relations` (array)
          for (int i = 0; i < jsonArrayrelations.size(); i++) {
            AllianceRelation.validateJsonElement(jsonArrayrelations.get(i));
          };
        }
      }
      // validate the optional field `primeBoost`
      if (jsonObj.get("primeBoost") != null && !jsonObj.get("primeBoost").isJsonNull()) {
        AlliancePrimeBoost.validateJsonElement(jsonObj.get("primeBoost"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AllianceEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AllianceEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AllianceEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AllianceEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<AllianceEntry>() {
           @Override
           public void write(JsonWriter out, AllianceEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AllianceEntry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AllianceEntry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AllianceEntry
   * @throws IOException if the JSON string is invalid with respect to AllianceEntry
   */
  public static AllianceEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AllianceEntry.class);
  }

  /**
   * Convert an instance of AllianceEntry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

