/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * Relation entre alliances
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class AllianceRelation {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_RELATION = "relation";
  @SerializedName(SERIALIZED_NAME_RELATION)
  @javax.annotation.Nullable
  private String relation;

  public static final String SERIALIZED_NAME_SURCHARGE_VALUE_FROM = "surchargeValueFrom";
  @SerializedName(SERIALIZED_NAME_SURCHARGE_VALUE_FROM)
  @javax.annotation.Nullable
  private Double surchargeValueFrom;

  public static final String SERIALIZED_NAME_HAS_EMBARGO_FROM = "hasEmbargoFrom";
  @SerializedName(SERIALIZED_NAME_HAS_EMBARGO_FROM)
  @javax.annotation.Nullable
  private Boolean hasEmbargoFrom;

  public static final String SERIALIZED_NAME_SURCHARGE_VALUE_TO = "surchargeValueTo";
  @SerializedName(SERIALIZED_NAME_SURCHARGE_VALUE_TO)
  @javax.annotation.Nullable
  private Double surchargeValueTo;

  public static final String SERIALIZED_NAME_HAS_EMBARGO_TO = "hasEmbargoTo";
  @SerializedName(SERIALIZED_NAME_HAS_EMBARGO_TO)
  @javax.annotation.Nullable
  private Boolean hasEmbargoTo;

  public AllianceRelation() {
  }

  public AllianceRelation name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Le nom de l&#39;alliance concerné par la relation
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public AllianceRelation relation(@javax.annotation.Nullable String relation) {
    this.relation = relation;
    return this;
  }

  /**
   * Le type de relation (neutral/enemy)
   * @return relation
   */
  @javax.annotation.Nullable
  public String getRelation() {
    return relation;
  }

  public void setRelation(@javax.annotation.Nullable String relation) {
    this.relation = relation;
  }


  public AllianceRelation surchargeValueFrom(@javax.annotation.Nullable Double surchargeValueFrom) {
    this.surchargeValueFrom = surchargeValueFrom;
    return this;
  }

  /**
   * Le pourcentage de surcharge appliqué par l&#39;alliance de la relation sur l&#39;alliance dont l&#39;export est fait
   * @return surchargeValueFrom
   */
  @javax.annotation.Nullable
  public Double getSurchargeValueFrom() {
    return surchargeValueFrom;
  }

  public void setSurchargeValueFrom(@javax.annotation.Nullable Double surchargeValueFrom) {
    this.surchargeValueFrom = surchargeValueFrom;
  }


  public AllianceRelation hasEmbargoFrom(@javax.annotation.Nullable Boolean hasEmbargoFrom) {
    this.hasEmbargoFrom = hasEmbargoFrom;
    return this;
  }

  /**
   * Si l&#39;alliance de la relation a appliqué un embargo sur l&#39;alliance dont l&#39;export est fait
   * @return hasEmbargoFrom
   */
  @javax.annotation.Nullable
  public Boolean getHasEmbargoFrom() {
    return hasEmbargoFrom;
  }

  public void setHasEmbargoFrom(@javax.annotation.Nullable Boolean hasEmbargoFrom) {
    this.hasEmbargoFrom = hasEmbargoFrom;
  }


  public AllianceRelation surchargeValueTo(@javax.annotation.Nullable Double surchargeValueTo) {
    this.surchargeValueTo = surchargeValueTo;
    return this;
  }

  /**
   * Le pourcentage de surcharge appliqué par l&#39;alliance dont l&#39;export est fait sur l&#39;alliance de la relation
   * @return surchargeValueTo
   */
  @javax.annotation.Nullable
  public Double getSurchargeValueTo() {
    return surchargeValueTo;
  }

  public void setSurchargeValueTo(@javax.annotation.Nullable Double surchargeValueTo) {
    this.surchargeValueTo = surchargeValueTo;
  }


  public AllianceRelation hasEmbargoTo(@javax.annotation.Nullable Boolean hasEmbargoTo) {
    this.hasEmbargoTo = hasEmbargoTo;
    return this;
  }

  /**
   * Si l&#39;alliance dont l&#39;export est fait a appliqué un embargo sur l&#39;alliance de la relation
   * @return hasEmbargoTo
   */
  @javax.annotation.Nullable
  public Boolean getHasEmbargoTo() {
    return hasEmbargoTo;
  }

  public void setHasEmbargoTo(@javax.annotation.Nullable Boolean hasEmbargoTo) {
    this.hasEmbargoTo = hasEmbargoTo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllianceRelation allianceRelation = (AllianceRelation) o;
    return Objects.equals(this.name, allianceRelation.name) &&
        Objects.equals(this.relation, allianceRelation.relation) &&
        Objects.equals(this.surchargeValueFrom, allianceRelation.surchargeValueFrom) &&
        Objects.equals(this.hasEmbargoFrom, allianceRelation.hasEmbargoFrom) &&
        Objects.equals(this.surchargeValueTo, allianceRelation.surchargeValueTo) &&
        Objects.equals(this.hasEmbargoTo, allianceRelation.hasEmbargoTo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, relation, surchargeValueFrom, hasEmbargoFrom, surchargeValueTo, hasEmbargoTo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllianceRelation {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    relation: ").append(toIndentedString(relation)).append("\n");
    sb.append("    surchargeValueFrom: ").append(toIndentedString(surchargeValueFrom)).append("\n");
    sb.append("    hasEmbargoFrom: ").append(toIndentedString(hasEmbargoFrom)).append("\n");
    sb.append("    surchargeValueTo: ").append(toIndentedString(surchargeValueTo)).append("\n");
    sb.append("    hasEmbargoTo: ").append(toIndentedString(hasEmbargoTo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "relation", "surchargeValueFrom", "hasEmbargoFrom", "surchargeValueTo", "hasEmbargoTo"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AllianceRelation
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AllianceRelation.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AllianceRelation is not found in the empty JSON string", AllianceRelation.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AllianceRelation.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AllianceRelation` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("relation") != null && !jsonObj.get("relation").isJsonNull()) && !jsonObj.get("relation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `relation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relation").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AllianceRelation.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AllianceRelation' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AllianceRelation> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AllianceRelation.class));

       return (TypeAdapter<T>) new TypeAdapter<AllianceRelation>() {
           @Override
           public void write(JsonWriter out, AllianceRelation value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AllianceRelation read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AllianceRelation given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AllianceRelation
   * @throws IOException if the JSON string is invalid with respect to AllianceRelation
   */
  public static AllianceRelation fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AllianceRelation.class);
  }

  /**
   * Convert an instance of AllianceRelation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

