/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * ArchitectureEntry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class ArchitectureEntry {
  public static final String SERIALIZED_NAME_TERRAFORMING = "terraforming";
  @SerializedName(SERIALIZED_NAME_TERRAFORMING)
  @javax.annotation.Nullable
  private Integer terraforming;

  public static final String SERIALIZED_NAME_COHERENCE_STYLE = "coherenceStyle";
  @SerializedName(SERIALIZED_NAME_COHERENCE_STYLE)
  @javax.annotation.Nullable
  private Integer coherenceStyle;

  public static final String SERIALIZED_NAME_ACTIVITE_RECENTE = "activiteRecente";
  @SerializedName(SERIALIZED_NAME_ACTIVITE_RECENTE)
  @javax.annotation.Nullable
  private Integer activiteRecente;

  public static final String SERIALIZED_NAME_BLOCS_CATALOGUE = "blocsCatalogue";
  @SerializedName(SERIALIZED_NAME_BLOCS_CATALOGUE)
  @javax.annotation.Nullable
  private Integer blocsCatalogue;

  public static final String SERIALIZED_NAME_TROU_MISSILES = "trouMissiles";
  @SerializedName(SERIALIZED_NAME_TROU_MISSILES)
  @javax.annotation.Nullable
  private Integer trouMissiles;

  public static final String SERIALIZED_NAME_BEAUTE_GENERALE = "beauteGenerale";
  @SerializedName(SERIALIZED_NAME_BEAUTE_GENERALE)
  @javax.annotation.Nullable
  private Double beauteGenerale;

  public static final String SERIALIZED_NAME_HABITABILITE_MAISON = "habitabiliteMaison";
  @SerializedName(SERIALIZED_NAME_HABITABILITE_MAISON)
  @javax.annotation.Nullable
  private Integer habitabiliteMaison;

  public static final String SERIALIZED_NAME_BIOME_COHERENT = "biomeCoherent";
  @SerializedName(SERIALIZED_NAME_BIOME_COHERENT)
  @javax.annotation.Nullable
  private Integer biomeCoherent;

  public static final String SERIALIZED_NAME_BATIMENTS_ABANDONNES = "batimentsAbandonnes";
  @SerializedName(SERIALIZED_NAME_BATIMENTS_ABANDONNES)
  @javax.annotation.Nullable
  private Integer batimentsAbandonnes;

  public static final String SERIALIZED_NAME_UTILISATION_SCHEMATICA = "utilisationSchematica";
  @SerializedName(SERIALIZED_NAME_UTILISATION_SCHEMATICA)
  @javax.annotation.Nullable
  private Integer utilisationSchematica;

  public static final String SERIALIZED_NAME_COHERENCE_LUMIERES = "coherenceLumieres";
  @SerializedName(SERIALIZED_NAME_COHERENCE_LUMIERES)
  @javax.annotation.Nullable
  private Integer coherenceLumieres;

  public static final String SERIALIZED_NAME_ROLEPLAY_PAYS = "roleplayPays";
  @SerializedName(SERIALIZED_NAME_ROLEPLAY_PAYS)
  @javax.annotation.Nullable
  private Integer roleplayPays;

  public static final String SERIALIZED_NAME_ORGANICS = "organics";
  @SerializedName(SERIALIZED_NAME_ORGANICS)
  @javax.annotation.Nullable
  private Integer organics;

  public static final String SERIALIZED_NAME_SURFACE_CONSTRUITE = "surfaceConstruite";
  @SerializedName(SERIALIZED_NAME_SURFACE_CONSTRUITE)
  @javax.annotation.Nullable
  private Double surfaceConstruite;

  public static final String SERIALIZED_NAME_STAFF = "staff";
  @SerializedName(SERIALIZED_NAME_STAFF)
  @javax.annotation.Nullable
  private String staff;

  public ArchitectureEntry() {
  }

  public ArchitectureEntry terraforming(@javax.annotation.Nullable Integer terraforming) {
    this.terraforming = terraforming;
    return this;
  }

  /**
   * Terraforming (entre 0 et 2)
   * @return terraforming
   */
  @javax.annotation.Nullable
  public Integer getTerraforming() {
    return terraforming;
  }

  public void setTerraforming(@javax.annotation.Nullable Integer terraforming) {
    this.terraforming = terraforming;
  }


  public ArchitectureEntry coherenceStyle(@javax.annotation.Nullable Integer coherenceStyle) {
    this.coherenceStyle = coherenceStyle;
    return this;
  }

  /**
   * Cohérence du style (entre 0 et 2)
   * @return coherenceStyle
   */
  @javax.annotation.Nullable
  public Integer getCoherenceStyle() {
    return coherenceStyle;
  }

  public void setCoherenceStyle(@javax.annotation.Nullable Integer coherenceStyle) {
    this.coherenceStyle = coherenceStyle;
  }


  public ArchitectureEntry activiteRecente(@javax.annotation.Nullable Integer activiteRecente) {
    this.activiteRecente = activiteRecente;
    return this;
  }

  /**
   * Activité récente (entre 0 et 4)
   * @return activiteRecente
   */
  @javax.annotation.Nullable
  public Integer getActiviteRecente() {
    return activiteRecente;
  }

  public void setActiviteRecente(@javax.annotation.Nullable Integer activiteRecente) {
    this.activiteRecente = activiteRecente;
  }


  public ArchitectureEntry blocsCatalogue(@javax.annotation.Nullable Integer blocsCatalogue) {
    this.blocsCatalogue = blocsCatalogue;
    return this;
  }

  /**
   * Utilisation de blocs du catalogue (entre 0 et 2)
   * @return blocsCatalogue
   */
  @javax.annotation.Nullable
  public Integer getBlocsCatalogue() {
    return blocsCatalogue;
  }

  public void setBlocsCatalogue(@javax.annotation.Nullable Integer blocsCatalogue) {
    this.blocsCatalogue = blocsCatalogue;
  }


  public ArchitectureEntry trouMissiles(@javax.annotation.Nullable Integer trouMissiles) {
    this.trouMissiles = trouMissiles;
    return this;
  }

  /**
   * Présence de trous de missiles (entre 0 et -4)
   * @return trouMissiles
   */
  @javax.annotation.Nullable
  public Integer getTrouMissiles() {
    return trouMissiles;
  }

  public void setTrouMissiles(@javax.annotation.Nullable Integer trouMissiles) {
    this.trouMissiles = trouMissiles;
  }


  public ArchitectureEntry beauteGenerale(@javax.annotation.Nullable Double beauteGenerale) {
    this.beauteGenerale = beauteGenerale;
    return this;
  }

  /**
   * Beauté générale du pays (entre 0 et 4)
   * @return beauteGenerale
   */
  @javax.annotation.Nullable
  public Double getBeauteGenerale() {
    return beauteGenerale;
  }

  public void setBeauteGenerale(@javax.annotation.Nullable Double beauteGenerale) {
    this.beauteGenerale = beauteGenerale;
  }


  public ArchitectureEntry habitabiliteMaison(@javax.annotation.Nullable Integer habitabiliteMaison) {
    this.habitabiliteMaison = habitabiliteMaison;
    return this;
  }

  /**
   * Habitabilité des maisons (entre 0 et 2)
   * @return habitabiliteMaison
   */
  @javax.annotation.Nullable
  public Integer getHabitabiliteMaison() {
    return habitabiliteMaison;
  }

  public void setHabitabiliteMaison(@javax.annotation.Nullable Integer habitabiliteMaison) {
    this.habitabiliteMaison = habitabiliteMaison;
  }


  public ArchitectureEntry biomeCoherent(@javax.annotation.Nullable Integer biomeCoherent) {
    this.biomeCoherent = biomeCoherent;
    return this;
  }

  /**
   * Cohérence avec le biome (entre 0 et 1)
   * @return biomeCoherent
   */
  @javax.annotation.Nullable
  public Integer getBiomeCoherent() {
    return biomeCoherent;
  }

  public void setBiomeCoherent(@javax.annotation.Nullable Integer biomeCoherent) {
    this.biomeCoherent = biomeCoherent;
  }


  public ArchitectureEntry batimentsAbandonnes(@javax.annotation.Nullable Integer batimentsAbandonnes) {
    this.batimentsAbandonnes = batimentsAbandonnes;
    return this;
  }

  /**
   * Absence de bâtiments abandonnés (1 si aucun, 0 sinon)
   * @return batimentsAbandonnes
   */
  @javax.annotation.Nullable
  public Integer getBatimentsAbandonnes() {
    return batimentsAbandonnes;
  }

  public void setBatimentsAbandonnes(@javax.annotation.Nullable Integer batimentsAbandonnes) {
    this.batimentsAbandonnes = batimentsAbandonnes;
  }


  public ArchitectureEntry utilisationSchematica(@javax.annotation.Nullable Integer utilisationSchematica) {
    this.utilisationSchematica = utilisationSchematica;
    return this;
  }

  /**
   * Utilisation de schematica (0 si non, -1 si oui)
   * @return utilisationSchematica
   */
  @javax.annotation.Nullable
  public Integer getUtilisationSchematica() {
    return utilisationSchematica;
  }

  public void setUtilisationSchematica(@javax.annotation.Nullable Integer utilisationSchematica) {
    this.utilisationSchematica = utilisationSchematica;
  }


  public ArchitectureEntry coherenceLumieres(@javax.annotation.Nullable Integer coherenceLumieres) {
    this.coherenceLumieres = coherenceLumieres;
    return this;
  }

  /**
   * Cohérence des lumières (entre 0 et 1)
   * @return coherenceLumieres
   */
  @javax.annotation.Nullable
  public Integer getCoherenceLumieres() {
    return coherenceLumieres;
  }

  public void setCoherenceLumieres(@javax.annotation.Nullable Integer coherenceLumieres) {
    this.coherenceLumieres = coherenceLumieres;
  }


  public ArchitectureEntry roleplayPays(@javax.annotation.Nullable Integer roleplayPays) {
    this.roleplayPays = roleplayPays;
    return this;
  }

  /**
   * Respect du roleplay du pays (entre 0 et 1)
   * @return roleplayPays
   */
  @javax.annotation.Nullable
  public Integer getRoleplayPays() {
    return roleplayPays;
  }

  public void setRoleplayPays(@javax.annotation.Nullable Integer roleplayPays) {
    this.roleplayPays = roleplayPays;
  }


  public ArchitectureEntry organics(@javax.annotation.Nullable Integer organics) {
    this.organics = organics;
    return this;
  }

  /**
   * Présence d&#39;organics (entre 0 et 1)
   * @return organics
   */
  @javax.annotation.Nullable
  public Integer getOrganics() {
    return organics;
  }

  public void setOrganics(@javax.annotation.Nullable Integer organics) {
    this.organics = organics;
  }


  public ArchitectureEntry surfaceConstruite(@javax.annotation.Nullable Double surfaceConstruite) {
    this.surfaceConstruite = surfaceConstruite;
    return this;
  }

  /**
   * Multiplicateur de surface construite (entre x0 et x2.0)
   * @return surfaceConstruite
   */
  @javax.annotation.Nullable
  public Double getSurfaceConstruite() {
    return surfaceConstruite;
  }

  public void setSurfaceConstruite(@javax.annotation.Nullable Double surfaceConstruite) {
    this.surfaceConstruite = surfaceConstruite;
  }


  public ArchitectureEntry staff(@javax.annotation.Nullable String staff) {
    this.staff = staff;
    return this;
  }

  /**
   * Le username du staff qui a noté le pays
   * @return staff
   */
  @javax.annotation.Nullable
  public String getStaff() {
    return staff;
  }

  public void setStaff(@javax.annotation.Nullable String staff) {
    this.staff = staff;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArchitectureEntry architectureEntry = (ArchitectureEntry) o;
    return Objects.equals(this.terraforming, architectureEntry.terraforming) &&
        Objects.equals(this.coherenceStyle, architectureEntry.coherenceStyle) &&
        Objects.equals(this.activiteRecente, architectureEntry.activiteRecente) &&
        Objects.equals(this.blocsCatalogue, architectureEntry.blocsCatalogue) &&
        Objects.equals(this.trouMissiles, architectureEntry.trouMissiles) &&
        Objects.equals(this.beauteGenerale, architectureEntry.beauteGenerale) &&
        Objects.equals(this.habitabiliteMaison, architectureEntry.habitabiliteMaison) &&
        Objects.equals(this.biomeCoherent, architectureEntry.biomeCoherent) &&
        Objects.equals(this.batimentsAbandonnes, architectureEntry.batimentsAbandonnes) &&
        Objects.equals(this.utilisationSchematica, architectureEntry.utilisationSchematica) &&
        Objects.equals(this.coherenceLumieres, architectureEntry.coherenceLumieres) &&
        Objects.equals(this.roleplayPays, architectureEntry.roleplayPays) &&
        Objects.equals(this.organics, architectureEntry.organics) &&
        Objects.equals(this.surfaceConstruite, architectureEntry.surfaceConstruite) &&
        Objects.equals(this.staff, architectureEntry.staff);
  }

  @Override
  public int hashCode() {
    return Objects.hash(terraforming, coherenceStyle, activiteRecente, blocsCatalogue, trouMissiles, beauteGenerale, habitabiliteMaison, biomeCoherent, batimentsAbandonnes, utilisationSchematica, coherenceLumieres, roleplayPays, organics, surfaceConstruite, staff);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArchitectureEntry {\n");
    sb.append("    terraforming: ").append(toIndentedString(terraforming)).append("\n");
    sb.append("    coherenceStyle: ").append(toIndentedString(coherenceStyle)).append("\n");
    sb.append("    activiteRecente: ").append(toIndentedString(activiteRecente)).append("\n");
    sb.append("    blocsCatalogue: ").append(toIndentedString(blocsCatalogue)).append("\n");
    sb.append("    trouMissiles: ").append(toIndentedString(trouMissiles)).append("\n");
    sb.append("    beauteGenerale: ").append(toIndentedString(beauteGenerale)).append("\n");
    sb.append("    habitabiliteMaison: ").append(toIndentedString(habitabiliteMaison)).append("\n");
    sb.append("    biomeCoherent: ").append(toIndentedString(biomeCoherent)).append("\n");
    sb.append("    batimentsAbandonnes: ").append(toIndentedString(batimentsAbandonnes)).append("\n");
    sb.append("    utilisationSchematica: ").append(toIndentedString(utilisationSchematica)).append("\n");
    sb.append("    coherenceLumieres: ").append(toIndentedString(coherenceLumieres)).append("\n");
    sb.append("    roleplayPays: ").append(toIndentedString(roleplayPays)).append("\n");
    sb.append("    organics: ").append(toIndentedString(organics)).append("\n");
    sb.append("    surfaceConstruite: ").append(toIndentedString(surfaceConstruite)).append("\n");
    sb.append("    staff: ").append(toIndentedString(staff)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("terraforming", "coherenceStyle", "activiteRecente", "blocsCatalogue", "trouMissiles", "beauteGenerale", "habitabiliteMaison", "biomeCoherent", "batimentsAbandonnes", "utilisationSchematica", "coherenceLumieres", "roleplayPays", "organics", "surfaceConstruite", "staff"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ArchitectureEntry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ArchitectureEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ArchitectureEntry is not found in the empty JSON string", ArchitectureEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ArchitectureEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ArchitectureEntry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("staff") != null && !jsonObj.get("staff").isJsonNull()) && !jsonObj.get("staff").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `staff` to be a primitive type in the JSON string but got `%s`", jsonObj.get("staff").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ArchitectureEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ArchitectureEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ArchitectureEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ArchitectureEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<ArchitectureEntry>() {
           @Override
           public void write(JsonWriter out, ArchitectureEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ArchitectureEntry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ArchitectureEntry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ArchitectureEntry
   * @throws IOException if the JSON string is invalid with respect to ArchitectureEntry
   */
  public static ArchitectureEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ArchitectureEntry.class);
  }

  /**
   * Convert an instance of ArchitectureEntry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

