/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import software.yoxo.client.model.LastResearchEntry;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * Données de R&amp;D pour un pays
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class CountryResearchEntry {
  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nullable
  private String country;

  public static final String SERIALIZED_NAME_RESEARCHES_LEVELS = "researchesLevels";
  @SerializedName(SERIALIZED_NAME_RESEARCHES_LEVELS)
  @javax.annotation.Nullable
  private Map<String, Integer> researchesLevels = new HashMap<>();

  public static final String SERIALIZED_NAME_LAST_RESEARCH = "lastResearch";
  @SerializedName(SERIALIZED_NAME_LAST_RESEARCH)
  @javax.annotation.Nullable
  private LastResearchEntry lastResearch;

  public static final String SERIALIZED_NAME_RESEARCHES_CONDITIONS_VALUES = "researchesConditionsValues";
  @SerializedName(SERIALIZED_NAME_RESEARCHES_CONDITIONS_VALUES)
  @javax.annotation.Nullable
  private Map<String, Double> researchesConditionsValues = new HashMap<>();

  public CountryResearchEntry() {
  }

  public CountryResearchEntry country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * Nom du pays
   * @return country
   */
  @javax.annotation.Nullable
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public CountryResearchEntry researchesLevels(@javax.annotation.Nullable Map<String, Integer> researchesLevels) {
    this.researchesLevels = researchesLevels;
    return this;
  }

  public CountryResearchEntry putResearchesLevelsItem(String key, Integer researchesLevelsItem) {
    if (this.researchesLevels == null) {
      this.researchesLevels = new HashMap<>();
    }
    this.researchesLevels.put(key, researchesLevelsItem);
    return this;
  }

  /**
   * Niveaux actuels de R&amp;D par branche
   * @return researchesLevels
   */
  @javax.annotation.Nullable
  public Map<String, Integer> getResearchesLevels() {
    return researchesLevels;
  }

  public void setResearchesLevels(@javax.annotation.Nullable Map<String, Integer> researchesLevels) {
    this.researchesLevels = researchesLevels;
  }


  public CountryResearchEntry lastResearch(@javax.annotation.Nullable LastResearchEntry lastResearch) {
    this.lastResearch = lastResearch;
    return this;
  }

  /**
   * Get lastResearch
   * @return lastResearch
   */
  @javax.annotation.Nullable
  public LastResearchEntry getLastResearch() {
    return lastResearch;
  }

  public void setLastResearch(@javax.annotation.Nullable LastResearchEntry lastResearch) {
    this.lastResearch = lastResearch;
  }


  public CountryResearchEntry researchesConditionsValues(@javax.annotation.Nullable Map<String, Double> researchesConditionsValues) {
    this.researchesConditionsValues = researchesConditionsValues;
    return this;
  }

  public CountryResearchEntry putResearchesConditionsValuesItem(String key, Double researchesConditionsValuesItem) {
    if (this.researchesConditionsValues == null) {
      this.researchesConditionsValues = new HashMap<>();
    }
    this.researchesConditionsValues.put(key, researchesConditionsValuesItem);
    return this;
  }

  /**
   * Valeurs actuelles des conditions de recherche. Celles-ci sont globales
   * @return researchesConditionsValues
   */
  @javax.annotation.Nullable
  public Map<String, Double> getResearchesConditionsValues() {
    return researchesConditionsValues;
  }

  public void setResearchesConditionsValues(@javax.annotation.Nullable Map<String, Double> researchesConditionsValues) {
    this.researchesConditionsValues = researchesConditionsValues;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountryResearchEntry countryResearchEntry = (CountryResearchEntry) o;
    return Objects.equals(this.country, countryResearchEntry.country) &&
        Objects.equals(this.researchesLevels, countryResearchEntry.researchesLevels) &&
        Objects.equals(this.lastResearch, countryResearchEntry.lastResearch) &&
        Objects.equals(this.researchesConditionsValues, countryResearchEntry.researchesConditionsValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, researchesLevels, lastResearch, researchesConditionsValues);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountryResearchEntry {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    researchesLevels: ").append(toIndentedString(researchesLevels)).append("\n");
    sb.append("    lastResearch: ").append(toIndentedString(lastResearch)).append("\n");
    sb.append("    researchesConditionsValues: ").append(toIndentedString(researchesConditionsValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("country", "researchesLevels", "lastResearch", "researchesConditionsValues"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CountryResearchEntry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CountryResearchEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CountryResearchEntry is not found in the empty JSON string", CountryResearchEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CountryResearchEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CountryResearchEntry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("country") != null && !jsonObj.get("country").isJsonNull()) && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      // validate the optional field `lastResearch`
      if (jsonObj.get("lastResearch") != null && !jsonObj.get("lastResearch").isJsonNull()) {
        LastResearchEntry.validateJsonElement(jsonObj.get("lastResearch"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CountryResearchEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CountryResearchEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CountryResearchEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CountryResearchEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<CountryResearchEntry>() {
           @Override
           public void write(JsonWriter out, CountryResearchEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CountryResearchEntry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CountryResearchEntry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CountryResearchEntry
   * @throws IOException if the JSON string is invalid with respect to CountryResearchEntry
   */
  public static CountryResearchEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CountryResearchEntry.class);
  }

  /**
   * Convert an instance of CountryResearchEntry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

