/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import software.yoxo.client.model.EnterpriseBank;
import software.yoxo.client.model.EnterpriseBetItem;
import software.yoxo.client.model.EnterpriseEntry;
import software.yoxo.client.model.EnterprisePermission;
import software.yoxo.client.model.Parcelle;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * Entreprise agricole
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class EnterpriseFarm extends EnterpriseEntry {
  public static final String SERIALIZED_NAME_HISTORIES = "histories";
  @SerializedName(SERIALIZED_NAME_HISTORIES)
  @javax.annotation.Nullable
  private Map<String, Map<String, Double>> histories = new HashMap<>();

  public static final String SERIALIZED_NAME_TOTAL_COLLECTED = "totalCollected";
  @SerializedName(SERIALIZED_NAME_TOTAL_COLLECTED)
  @javax.annotation.Nullable
  private Integer totalCollected;

  public static final String SERIALIZED_NAME_COLLECTED_CEREAL = "collectedCereal";
  @SerializedName(SERIALIZED_NAME_COLLECTED_CEREAL)
  @javax.annotation.Nullable
  private Map<String, Integer> collectedCereal = new HashMap<>();

  public EnterpriseFarm() {

  }

  public EnterpriseFarm histories(@javax.annotation.Nullable Map<String, Map<String, Double>> histories) {
    this.histories = histories;
    return this;
  }

  public EnterpriseFarm putHistoriesItem(String key, Map<String, Double> historiesItem) {
    if (this.histories == null) {
      this.histories = new HashMap<>();
    }
    this.histories.put(key, historiesItem);
    return this;
  }

  /**
   * Historiques des ventes par céréale et date
   * @return histories
   */
  @javax.annotation.Nullable
  public Map<String, Map<String, Double>> getHistories() {
    return histories;
  }

  public void setHistories(@javax.annotation.Nullable Map<String, Map<String, Double>> histories) {
    this.histories = histories;
  }


  public EnterpriseFarm totalCollected(@javax.annotation.Nullable Integer totalCollected) {
    this.totalCollected = totalCollected;
    return this;
  }

  /**
   * Poids total de céréale vendu depuis la création de l&#39;entreprise (en kg)
   * @return totalCollected
   */
  @javax.annotation.Nullable
  public Integer getTotalCollected() {
    return totalCollected;
  }

  public void setTotalCollected(@javax.annotation.Nullable Integer totalCollected) {
    this.totalCollected = totalCollected;
  }


  public EnterpriseFarm collectedCereal(@javax.annotation.Nullable Map<String, Integer> collectedCereal) {
    this.collectedCereal = collectedCereal;
    return this;
  }

  public EnterpriseFarm putCollectedCerealItem(String key, Integer collectedCerealItem) {
    if (this.collectedCereal == null) {
      this.collectedCereal = new HashMap<>();
    }
    this.collectedCereal.put(key, collectedCerealItem);
    return this;
  }

  /**
   * Poids total de céréales collectées (pour chaque céréale)
   * @return collectedCereal
   */
  @javax.annotation.Nullable
  public Map<String, Integer> getCollectedCereal() {
    return collectedCereal;
  }

  public void setCollectedCereal(@javax.annotation.Nullable Map<String, Integer> collectedCereal) {
    this.collectedCereal = collectedCereal;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnterpriseFarm enterpriseFarm = (EnterpriseFarm) o;
    return Objects.equals(this.histories, enterpriseFarm.histories) &&
        Objects.equals(this.totalCollected, enterpriseFarm.totalCollected) &&
        Objects.equals(this.collectedCereal, enterpriseFarm.collectedCereal) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(histories, totalCollected, collectedCereal, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseFarm {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    histories: ").append(toIndentedString(histories)).append("\n");
    sb.append("    totalCollected: ").append(toIndentedString(totalCollected)).append("\n");
    sb.append("    collectedCereal: ").append(toIndentedString(collectedCereal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "name", "age", "description", "services", "owner", "flag", "cadres", "employees", "contractsDone", "disputes", "contractsSuccess", "turnover", "permissions", "bank", "bets", "betsRewardRedistributed", "betTotal", "betActive", "history", "benefAverage", "totalPlay", "winPercent", "totalWin", "total", "available", "allowCountry", "allowAlly", "allowAll", "associatedCountry", "price", "priceAverage", "countriesSell", "historyGenerated", "historyCollected", "histories", "totalCollected", "collectedCereal", "parcelles", "totalGenerated", "sumInvestment", "totalInvestors"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EnterpriseFarm
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EnterpriseFarm.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EnterpriseFarm is not found in the empty JSON string", EnterpriseFarm.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EnterpriseFarm.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EnterpriseFarm` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EnterpriseFarm.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EnterpriseFarm' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EnterpriseFarm> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EnterpriseFarm.class));

       return (TypeAdapter<T>) new TypeAdapter<EnterpriseFarm>() {
           @Override
           public void write(JsonWriter out, EnterpriseFarm value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EnterpriseFarm read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EnterpriseFarm given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EnterpriseFarm
   * @throws IOException if the JSON string is invalid with respect to EnterpriseFarm
   */
  public static EnterpriseFarm fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EnterpriseFarm.class);
  }

  /**
   * Convert an instance of EnterpriseFarm to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

