/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import software.yoxo.client.model.EnterpriseBank;
import software.yoxo.client.model.EnterpriseBetItem;
import software.yoxo.client.model.EnterpriseEntry;
import software.yoxo.client.model.EnterprisePermission;
import software.yoxo.client.model.Parcelle;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * Entreprise casino
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class EnterpriseCasino extends EnterpriseEntry {
  public static final String SERIALIZED_NAME_HISTORY = "history";
  @SerializedName(SERIALIZED_NAME_HISTORY)
  @javax.annotation.Nullable
  private Map<String, Double> history = new HashMap<>();

  public static final String SERIALIZED_NAME_BENEF_AVERAGE = "benefAverage";
  @SerializedName(SERIALIZED_NAME_BENEF_AVERAGE)
  @javax.annotation.Nullable
  private Double benefAverage;

  public static final String SERIALIZED_NAME_TOTAL_PLAY = "totalPlay";
  @SerializedName(SERIALIZED_NAME_TOTAL_PLAY)
  @javax.annotation.Nullable
  private Double totalPlay;

  public static final String SERIALIZED_NAME_WIN_PERCENT = "winPercent";
  @SerializedName(SERIALIZED_NAME_WIN_PERCENT)
  @javax.annotation.Nullable
  private Double winPercent;

  public static final String SERIALIZED_NAME_TOTAL_WIN = "totalWin";
  @SerializedName(SERIALIZED_NAME_TOTAL_WIN)
  @javax.annotation.Nullable
  private Double totalWin;

  public EnterpriseCasino() {

  }

  public EnterpriseCasino history(@javax.annotation.Nullable Map<String, Double> history) {
    this.history = history;
    return this;
  }

  public EnterpriseCasino putHistoryItem(String key, Double historyItem) {
    if (this.history == null) {
      this.history = new HashMap<>();
    }
    this.history.put(key, historyItem);
    return this;
  }

  /**
   * Historique des bénéfices du casino par date
   * @return history
   */
  @javax.annotation.Nullable
  public Map<String, Double> getHistory() {
    return history;
  }

  public void setHistory(@javax.annotation.Nullable Map<String, Double> history) {
    this.history = history;
  }


  public EnterpriseCasino benefAverage(@javax.annotation.Nullable Double benefAverage) {
    this.benefAverage = benefAverage;
    return this;
  }

  /**
   * Bénéfice moyen (par jours)
   * @return benefAverage
   */
  @javax.annotation.Nullable
  public Double getBenefAverage() {
    return benefAverage;
  }

  public void setBenefAverage(@javax.annotation.Nullable Double benefAverage) {
    this.benefAverage = benefAverage;
  }


  public EnterpriseCasino totalPlay(@javax.annotation.Nullable Double totalPlay) {
    this.totalPlay = totalPlay;
    return this;
  }

  /**
   * Sommes totale jouée
   * @return totalPlay
   */
  @javax.annotation.Nullable
  public Double getTotalPlay() {
    return totalPlay;
  }

  public void setTotalPlay(@javax.annotation.Nullable Double totalPlay) {
    this.totalPlay = totalPlay;
  }


  public EnterpriseCasino winPercent(@javax.annotation.Nullable Double winPercent) {
    this.winPercent = winPercent;
    return this;
  }

  /**
   * Taux de redistribution des gains (en pourcentage)
   * @return winPercent
   */
  @javax.annotation.Nullable
  public Double getWinPercent() {
    return winPercent;
  }

  public void setWinPercent(@javax.annotation.Nullable Double winPercent) {
    this.winPercent = winPercent;
  }


  public EnterpriseCasino totalWin(@javax.annotation.Nullable Double totalWin) {
    this.totalWin = totalWin;
    return this;
  }

  /**
   * Somme totale des gains distribuées aux joueurs
   * @return totalWin
   */
  @javax.annotation.Nullable
  public Double getTotalWin() {
    return totalWin;
  }

  public void setTotalWin(@javax.annotation.Nullable Double totalWin) {
    this.totalWin = totalWin;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnterpriseCasino enterpriseCasino = (EnterpriseCasino) o;
    return Objects.equals(this.history, enterpriseCasino.history) &&
        Objects.equals(this.benefAverage, enterpriseCasino.benefAverage) &&
        Objects.equals(this.totalPlay, enterpriseCasino.totalPlay) &&
        Objects.equals(this.winPercent, enterpriseCasino.winPercent) &&
        Objects.equals(this.totalWin, enterpriseCasino.totalWin) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(history, benefAverage, totalPlay, winPercent, totalWin, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseCasino {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("    benefAverage: ").append(toIndentedString(benefAverage)).append("\n");
    sb.append("    totalPlay: ").append(toIndentedString(totalPlay)).append("\n");
    sb.append("    winPercent: ").append(toIndentedString(winPercent)).append("\n");
    sb.append("    totalWin: ").append(toIndentedString(totalWin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "name", "age", "description", "services", "owner", "flag", "cadres", "employees", "contractsDone", "disputes", "contractsSuccess", "turnover", "permissions", "bank", "bets", "betsRewardRedistributed", "betTotal", "betActive", "history", "benefAverage", "totalPlay", "winPercent", "totalWin", "total", "available", "allowCountry", "allowAlly", "allowAll", "associatedCountry", "price", "priceAverage", "countriesSell", "historyGenerated", "historyCollected", "histories", "totalCollected", "collectedCereal", "parcelles", "totalGenerated", "sumInvestment", "totalInvestors"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EnterpriseCasino
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EnterpriseCasino.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EnterpriseCasino is not found in the empty JSON string", EnterpriseCasino.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EnterpriseCasino.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EnterpriseCasino` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EnterpriseCasino.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EnterpriseCasino' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EnterpriseCasino> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EnterpriseCasino.class));

       return (TypeAdapter<T>) new TypeAdapter<EnterpriseCasino>() {
           @Override
           public void write(JsonWriter out, EnterpriseCasino value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EnterpriseCasino read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EnterpriseCasino given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EnterpriseCasino
   * @throws IOException if the JSON string is invalid with respect to EnterpriseCasino
   */
  public static EnterpriseCasino fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EnterpriseCasino.class);
  }

  /**
   * Convert an instance of EnterpriseCasino to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

