/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import software.yoxo.client.model.EnterpriseBank;
import software.yoxo.client.model.EnterprisePermission;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * Entreprise de trading
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class EnterpriseTrader {
  /**
   * Type d&#39;entreprise
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    BUILD("build"),
    
    ENGINEER("engineer"),
    
    TERRAFORM("terraform"),
    
    JOURNALIST("journalist"),
    
    CASINO("casino"),
    
    PVP("pvp"),
    
    LOAN("loan"),
    
    REALESTATE("realestate"),
    
    TRADER("trader"),
    
    BET("bet"),
    
    REPAIR("repair"),
    
    LAWYER("lawyer"),
    
    ELECTRIC("electric"),
    
    PETROL("petrol"),
    
    FARM("farm");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private TypeEnum type;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_AGE = "age";
  @SerializedName(SERIALIZED_NAME_AGE)
  @javax.annotation.Nullable
  private Integer age;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_SERVICES = "services";
  @SerializedName(SERIALIZED_NAME_SERVICES)
  @javax.annotation.Nullable
  private String services;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  @javax.annotation.Nullable
  private String owner;

  public static final String SERIALIZED_NAME_FLAG = "flag";
  @SerializedName(SERIALIZED_NAME_FLAG)
  @javax.annotation.Nullable
  private String flag;

  public static final String SERIALIZED_NAME_CADRES = "cadres";
  @SerializedName(SERIALIZED_NAME_CADRES)
  @javax.annotation.Nullable
  private List<String> cadres = new ArrayList<>();

  public static final String SERIALIZED_NAME_EMPLOYEES = "employees";
  @SerializedName(SERIALIZED_NAME_EMPLOYEES)
  @javax.annotation.Nullable
  private List<String> employees = new ArrayList<>();

  public static final String SERIALIZED_NAME_CONTRACTS_DONE = "contractsDone";
  @SerializedName(SERIALIZED_NAME_CONTRACTS_DONE)
  @javax.annotation.Nullable
  private Integer contractsDone;

  public static final String SERIALIZED_NAME_DISPUTES = "disputes";
  @SerializedName(SERIALIZED_NAME_DISPUTES)
  @javax.annotation.Nullable
  private Integer disputes;

  public static final String SERIALIZED_NAME_CONTRACTS_SUCCESS = "contractsSuccess";
  @SerializedName(SERIALIZED_NAME_CONTRACTS_SUCCESS)
  @javax.annotation.Nullable
  private Double contractsSuccess;

  public static final String SERIALIZED_NAME_TURNOVER = "turnover";
  @SerializedName(SERIALIZED_NAME_TURNOVER)
  @javax.annotation.Nullable
  private Integer turnover;

  public static final String SERIALIZED_NAME_PERMISSIONS = "permissions";
  @SerializedName(SERIALIZED_NAME_PERMISSIONS)
  @javax.annotation.Nullable
  private List<EnterprisePermission> permissions = new ArrayList<>();

  public static final String SERIALIZED_NAME_BANK = "bank";
  @SerializedName(SERIALIZED_NAME_BANK)
  @javax.annotation.Nullable
  private EnterpriseBank bank;

  public static final String SERIALIZED_NAME_HISTORY = "history";
  @SerializedName(SERIALIZED_NAME_HISTORY)
  @javax.annotation.Nullable
  private Map<String, Double> history = new HashMap<>();

  public static final String SERIALIZED_NAME_TOTAL_GENERATED = "totalGenerated";
  @SerializedName(SERIALIZED_NAME_TOTAL_GENERATED)
  @javax.annotation.Nullable
  private Integer totalGenerated;

  public static final String SERIALIZED_NAME_SUM_INVESTMENT = "sumInvestment";
  @SerializedName(SERIALIZED_NAME_SUM_INVESTMENT)
  @javax.annotation.Nullable
  private Float sumInvestment;

  public static final String SERIALIZED_NAME_TOTAL_INVESTORS = "totalInvestors";
  @SerializedName(SERIALIZED_NAME_TOTAL_INVESTORS)
  @javax.annotation.Nullable
  private Integer totalInvestors;

  public EnterpriseTrader() {
  }

  public EnterpriseTrader type(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Type d&#39;entreprise
   * @return type
   */
  @javax.annotation.Nullable
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable TypeEnum type) {
    this.type = type;
  }


  public EnterpriseTrader name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Nom de l&#39;entreprise
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public EnterpriseTrader age(@javax.annotation.Nullable Integer age) {
    this.age = age;
    return this;
  }

  /**
   * Âge de l&#39;entreprise en jours
   * @return age
   */
  @javax.annotation.Nullable
  public Integer getAge() {
    return age;
  }

  public void setAge(@javax.annotation.Nullable Integer age) {
    this.age = age;
  }


  public EnterpriseTrader description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Description de l&#39;entreprise
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public EnterpriseTrader services(@javax.annotation.Nullable String services) {
    this.services = services;
    return this;
  }

  /**
   * Services proposés
   * @return services
   */
  @javax.annotation.Nullable
  public String getServices() {
    return services;
  }

  public void setServices(@javax.annotation.Nullable String services) {
    this.services = services;
  }


  public EnterpriseTrader owner(@javax.annotation.Nullable String owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Propriétaire de l&#39;entreprise
   * @return owner
   */
  @javax.annotation.Nullable
  public String getOwner() {
    return owner;
  }

  public void setOwner(@javax.annotation.Nullable String owner) {
    this.owner = owner;
  }


  public EnterpriseTrader flag(@javax.annotation.Nullable String flag) {
    this.flag = flag;
    return this;
  }

  /**
   * Drapeau de l&#39;entreprise, sous la forme d&#39;image en Base64
   * @return flag
   */
  @javax.annotation.Nullable
  public String getFlag() {
    return flag;
  }

  public void setFlag(@javax.annotation.Nullable String flag) {
    this.flag = flag;
  }


  public EnterpriseTrader cadres(@javax.annotation.Nullable List<String> cadres) {
    this.cadres = cadres;
    return this;
  }

  public EnterpriseTrader addCadresItem(String cadresItem) {
    if (this.cadres == null) {
      this.cadres = new ArrayList<>();
    }
    this.cadres.add(cadresItem);
    return this;
  }

  /**
   * Liste des cadres de l&#39;entreprise
   * @return cadres
   */
  @javax.annotation.Nullable
  public List<String> getCadres() {
    return cadres;
  }

  public void setCadres(@javax.annotation.Nullable List<String> cadres) {
    this.cadres = cadres;
  }


  public EnterpriseTrader employees(@javax.annotation.Nullable List<String> employees) {
    this.employees = employees;
    return this;
  }

  public EnterpriseTrader addEmployeesItem(String employeesItem) {
    if (this.employees == null) {
      this.employees = new ArrayList<>();
    }
    this.employees.add(employeesItem);
    return this;
  }

  /**
   * Liste des employés de l&#39;entreprise
   * @return employees
   */
  @javax.annotation.Nullable
  public List<String> getEmployees() {
    return employees;
  }

  public void setEmployees(@javax.annotation.Nullable List<String> employees) {
    this.employees = employees;
  }


  public EnterpriseTrader contractsDone(@javax.annotation.Nullable Integer contractsDone) {
    this.contractsDone = contractsDone;
    return this;
  }

  /**
   * Nombre de contrats réalisés
   * @return contractsDone
   */
  @javax.annotation.Nullable
  public Integer getContractsDone() {
    return contractsDone;
  }

  public void setContractsDone(@javax.annotation.Nullable Integer contractsDone) {
    this.contractsDone = contractsDone;
  }


  public EnterpriseTrader disputes(@javax.annotation.Nullable Integer disputes) {
    this.disputes = disputes;
    return this;
  }

  /**
   * Nombre de litiges
   * @return disputes
   */
  @javax.annotation.Nullable
  public Integer getDisputes() {
    return disputes;
  }

  public void setDisputes(@javax.annotation.Nullable Integer disputes) {
    this.disputes = disputes;
  }


  public EnterpriseTrader contractsSuccess(@javax.annotation.Nullable Double contractsSuccess) {
    this.contractsSuccess = contractsSuccess;
    return this;
  }

  /**
   * Taux de réussite des contrats (pourcentage)
   * @return contractsSuccess
   */
  @javax.annotation.Nullable
  public Double getContractsSuccess() {
    return contractsSuccess;
  }

  public void setContractsSuccess(@javax.annotation.Nullable Double contractsSuccess) {
    this.contractsSuccess = contractsSuccess;
  }


  public EnterpriseTrader turnover(@javax.annotation.Nullable Integer turnover) {
    this.turnover = turnover;
    return this;
  }

  /**
   * Chiffre d&#39;affaires total
   * @return turnover
   */
  @javax.annotation.Nullable
  public Integer getTurnover() {
    return turnover;
  }

  public void setTurnover(@javax.annotation.Nullable Integer turnover) {
    this.turnover = turnover;
  }


  public EnterpriseTrader permissions(@javax.annotation.Nullable List<EnterprisePermission> permissions) {
    this.permissions = permissions;
    return this;
  }

  public EnterpriseTrader addPermissionsItem(EnterprisePermission permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

  /**
   * Permissions de l&#39;entreprise
   * @return permissions
   */
  @javax.annotation.Nullable
  public List<EnterprisePermission> getPermissions() {
    return permissions;
  }

  public void setPermissions(@javax.annotation.Nullable List<EnterprisePermission> permissions) {
    this.permissions = permissions;
  }


  public EnterpriseTrader bank(@javax.annotation.Nullable EnterpriseBank bank) {
    this.bank = bank;
    return this;
  }

  /**
   * Get bank
   * @return bank
   */
  @javax.annotation.Nullable
  public EnterpriseBank getBank() {
    return bank;
  }

  public void setBank(@javax.annotation.Nullable EnterpriseBank bank) {
    this.bank = bank;
  }


  public EnterpriseTrader history(@javax.annotation.Nullable Map<String, Double> history) {
    this.history = history;
    return this;
  }

  public EnterpriseTrader putHistoryItem(String key, Double historyItem) {
    if (this.history == null) {
      this.history = new HashMap<>();
    }
    this.history.put(key, historyItem);
    return this;
  }

  /**
   * Historique des rendements journaliers par date
   * @return history
   */
  @javax.annotation.Nullable
  public Map<String, Double> getHistory() {
    return history;
  }

  public void setHistory(@javax.annotation.Nullable Map<String, Double> history) {
    this.history = history;
  }


  public EnterpriseTrader totalGenerated(@javax.annotation.Nullable Integer totalGenerated) {
    this.totalGenerated = totalGenerated;
    return this;
  }

  /**
   * Argent total généré
   * @return totalGenerated
   */
  @javax.annotation.Nullable
  public Integer getTotalGenerated() {
    return totalGenerated;
  }

  public void setTotalGenerated(@javax.annotation.Nullable Integer totalGenerated) {
    this.totalGenerated = totalGenerated;
  }


  public EnterpriseTrader sumInvestment(@javax.annotation.Nullable Float sumInvestment) {
    this.sumInvestment = sumInvestment;
    return this;
  }

  /**
   * Somme totale investie par l&#39;ensemble des investisseurs
   * @return sumInvestment
   */
  @javax.annotation.Nullable
  public Float getSumInvestment() {
    return sumInvestment;
  }

  public void setSumInvestment(@javax.annotation.Nullable Float sumInvestment) {
    this.sumInvestment = sumInvestment;
  }


  public EnterpriseTrader totalInvestors(@javax.annotation.Nullable Integer totalInvestors) {
    this.totalInvestors = totalInvestors;
    return this;
  }

  /**
   * Nombre total d&#39;investisseurs
   * @return totalInvestors
   */
  @javax.annotation.Nullable
  public Integer getTotalInvestors() {
    return totalInvestors;
  }

  public void setTotalInvestors(@javax.annotation.Nullable Integer totalInvestors) {
    this.totalInvestors = totalInvestors;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnterpriseTrader enterpriseTrader = (EnterpriseTrader) o;
    return Objects.equals(this.type, enterpriseTrader.type) &&
        Objects.equals(this.name, enterpriseTrader.name) &&
        Objects.equals(this.age, enterpriseTrader.age) &&
        Objects.equals(this.description, enterpriseTrader.description) &&
        Objects.equals(this.services, enterpriseTrader.services) &&
        Objects.equals(this.owner, enterpriseTrader.owner) &&
        Objects.equals(this.flag, enterpriseTrader.flag) &&
        Objects.equals(this.cadres, enterpriseTrader.cadres) &&
        Objects.equals(this.employees, enterpriseTrader.employees) &&
        Objects.equals(this.contractsDone, enterpriseTrader.contractsDone) &&
        Objects.equals(this.disputes, enterpriseTrader.disputes) &&
        Objects.equals(this.contractsSuccess, enterpriseTrader.contractsSuccess) &&
        Objects.equals(this.turnover, enterpriseTrader.turnover) &&
        Objects.equals(this.permissions, enterpriseTrader.permissions) &&
        Objects.equals(this.bank, enterpriseTrader.bank) &&
        Objects.equals(this.history, enterpriseTrader.history) &&
        Objects.equals(this.totalGenerated, enterpriseTrader.totalGenerated) &&
        Objects.equals(this.sumInvestment, enterpriseTrader.sumInvestment) &&
        Objects.equals(this.totalInvestors, enterpriseTrader.totalInvestors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, name, age, description, services, owner, flag, cadres, employees, contractsDone, disputes, contractsSuccess, turnover, permissions, bank, history, totalGenerated, sumInvestment, totalInvestors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnterpriseTrader {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    age: ").append(toIndentedString(age)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    flag: ").append(toIndentedString(flag)).append("\n");
    sb.append("    cadres: ").append(toIndentedString(cadres)).append("\n");
    sb.append("    employees: ").append(toIndentedString(employees)).append("\n");
    sb.append("    contractsDone: ").append(toIndentedString(contractsDone)).append("\n");
    sb.append("    disputes: ").append(toIndentedString(disputes)).append("\n");
    sb.append("    contractsSuccess: ").append(toIndentedString(contractsSuccess)).append("\n");
    sb.append("    turnover: ").append(toIndentedString(turnover)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("    totalGenerated: ").append(toIndentedString(totalGenerated)).append("\n");
    sb.append("    sumInvestment: ").append(toIndentedString(sumInvestment)).append("\n");
    sb.append("    totalInvestors: ").append(toIndentedString(totalInvestors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "name", "age", "description", "services", "owner", "flag", "cadres", "employees", "contractsDone", "disputes", "contractsSuccess", "turnover", "permissions", "bank", "history", "totalGenerated", "sumInvestment", "totalInvestors"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EnterpriseTrader
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EnterpriseTrader.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EnterpriseTrader is not found in the empty JSON string", EnterpriseTrader.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EnterpriseTrader.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EnterpriseTrader` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        TypeEnum.validateJsonElement(jsonObj.get("type"));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("services") != null && !jsonObj.get("services").isJsonNull()) && !jsonObj.get("services").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `services` to be a primitive type in the JSON string but got `%s`", jsonObj.get("services").toString()));
      }
      if ((jsonObj.get("owner") != null && !jsonObj.get("owner").isJsonNull()) && !jsonObj.get("owner").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `owner` to be a primitive type in the JSON string but got `%s`", jsonObj.get("owner").toString()));
      }
      if ((jsonObj.get("flag") != null && !jsonObj.get("flag").isJsonNull()) && !jsonObj.get("flag").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `flag` to be a primitive type in the JSON string but got `%s`", jsonObj.get("flag").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("cadres") != null && !jsonObj.get("cadres").isJsonNull() && !jsonObj.get("cadres").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `cadres` to be an array in the JSON string but got `%s`", jsonObj.get("cadres").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("employees") != null && !jsonObj.get("employees").isJsonNull() && !jsonObj.get("employees").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `employees` to be an array in the JSON string but got `%s`", jsonObj.get("employees").toString()));
      }
      if (jsonObj.get("permissions") != null && !jsonObj.get("permissions").isJsonNull()) {
        JsonArray jsonArraypermissions = jsonObj.getAsJsonArray("permissions");
        if (jsonArraypermissions != null) {
          // ensure the json data is an array
          if (!jsonObj.get("permissions").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `permissions` to be an array in the JSON string but got `%s`", jsonObj.get("permissions").toString()));
          }

          // validate the optional field `permissions` (array)
          for (int i = 0; i < jsonArraypermissions.size(); i++) {
            EnterprisePermission.validateJsonElement(jsonArraypermissions.get(i));
          };
        }
      }
      // validate the optional field `bank`
      if (jsonObj.get("bank") != null && !jsonObj.get("bank").isJsonNull()) {
        EnterpriseBank.validateJsonElement(jsonObj.get("bank"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EnterpriseTrader.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EnterpriseTrader' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EnterpriseTrader> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EnterpriseTrader.class));

       return (TypeAdapter<T>) new TypeAdapter<EnterpriseTrader>() {
           @Override
           public void write(JsonWriter out, EnterpriseTrader value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EnterpriseTrader read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EnterpriseTrader given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EnterpriseTrader
   * @throws IOException if the JSON string is invalid with respect to EnterpriseTrader
   */
  public static EnterpriseTrader fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EnterpriseTrader.class);
  }

  /**
   * Convert an instance of EnterpriseTrader to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

