/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * PlayerListEntry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class PlayerListEntry {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nullable
  private String country;

  public static final String SERIALIZED_NAME_POWER = "power";
  @SerializedName(SERIALIZED_NAME_POWER)
  @javax.annotation.Nullable
  private Integer power;

  public static final String SERIALIZED_NAME_POWER_MAX = "powerMax";
  @SerializedName(SERIALIZED_NAME_POWER_MAX)
  @javax.annotation.Nullable
  private Integer powerMax;

  public static final String SERIALIZED_NAME_PLAYTIME = "playtime";
  @SerializedName(SERIALIZED_NAME_PLAYTIME)
  @javax.annotation.Nullable
  private Integer playtime;

  public static final String SERIALIZED_NAME_LAST_LOGIN = "lastLogin";
  @SerializedName(SERIALIZED_NAME_LAST_LOGIN)
  @javax.annotation.Nullable
  private Long lastLogin;

  public PlayerListEntry() {
  }

  public PlayerListEntry name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Le pseudonyme du joueur
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public PlayerListEntry country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * Le pays du joueur, écrit en toutes lettres. Si le joueur est sans pays, la chaine retourné sera vide
   * @return country
   */
  @javax.annotation.Nullable
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public PlayerListEntry power(@javax.annotation.Nullable Integer power) {
    this.power = power;
    return this;
  }

  /**
   * Le power actuel du joueur
   * @return power
   */
  @javax.annotation.Nullable
  public Integer getPower() {
    return power;
  }

  public void setPower(@javax.annotation.Nullable Integer power) {
    this.power = power;
  }


  public PlayerListEntry powerMax(@javax.annotation.Nullable Integer powerMax) {
    this.powerMax = powerMax;
    return this;
  }

  /**
   * Le power maximum atteignable par le joueur
   * @return powerMax
   */
  @javax.annotation.Nullable
  public Integer getPowerMax() {
    return powerMax;
  }

  public void setPowerMax(@javax.annotation.Nullable Integer powerMax) {
    this.powerMax = powerMax;
  }


  public PlayerListEntry playtime(@javax.annotation.Nullable Integer playtime) {
    this.playtime = playtime;
    return this;
  }

  /**
   * Le temps de jeu total du joueur sur le serveur (en secondes)
   * @return playtime
   */
  @javax.annotation.Nullable
  public Integer getPlaytime() {
    return playtime;
  }

  public void setPlaytime(@javax.annotation.Nullable Integer playtime) {
    this.playtime = playtime;
  }


  public PlayerListEntry lastLogin(@javax.annotation.Nullable Long lastLogin) {
    this.lastLogin = lastLogin;
    return this;
  }

  /**
   * Le timestamp de la dernière connexion du joueur. Le timestamp est ici exprimé en secondes et correspond au nombre de secondes écoulées depuis le 1er janvier 1970, minuit UTC
   * @return lastLogin
   */
  @javax.annotation.Nullable
  public Long getLastLogin() {
    return lastLogin;
  }

  public void setLastLogin(@javax.annotation.Nullable Long lastLogin) {
    this.lastLogin = lastLogin;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerListEntry playerListEntry = (PlayerListEntry) o;
    return Objects.equals(this.name, playerListEntry.name) &&
        Objects.equals(this.country, playerListEntry.country) &&
        Objects.equals(this.power, playerListEntry.power) &&
        Objects.equals(this.powerMax, playerListEntry.powerMax) &&
        Objects.equals(this.playtime, playerListEntry.playtime) &&
        Objects.equals(this.lastLogin, playerListEntry.lastLogin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, country, power, powerMax, playtime, lastLogin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerListEntry {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    power: ").append(toIndentedString(power)).append("\n");
    sb.append("    powerMax: ").append(toIndentedString(powerMax)).append("\n");
    sb.append("    playtime: ").append(toIndentedString(playtime)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "country", "power", "powerMax", "playtime", "lastLogin"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PlayerListEntry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PlayerListEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PlayerListEntry is not found in the empty JSON string", PlayerListEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PlayerListEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PlayerListEntry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("country") != null && !jsonObj.get("country").isJsonNull()) && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PlayerListEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PlayerListEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PlayerListEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PlayerListEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<PlayerListEntry>() {
           @Override
           public void write(JsonWriter out, PlayerListEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PlayerListEntry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PlayerListEntry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PlayerListEntry
   * @throws IOException if the JSON string is invalid with respect to PlayerListEntry
   */
  public static PlayerListEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PlayerListEntry.class);
  }

  /**
   * Convert an instance of PlayerListEntry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

