/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * Détails d&#39;un assaut au sein de la guerre
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class WarAssault {
  public static final String SERIALIZED_NAME_START_AT = "startAt";
  @SerializedName(SERIALIZED_NAME_START_AT)
  @javax.annotation.Nullable
  private Long startAt;

  public static final String SERIALIZED_NAME_WINNER = "winner";
  @SerializedName(SERIALIZED_NAME_WINNER)
  @javax.annotation.Nullable
  private String winner;

  public static final String SERIALIZED_NAME_LOOSER = "looser";
  @SerializedName(SERIALIZED_NAME_LOOSER)
  @javax.annotation.Nullable
  private String looser;

  public static final String SERIALIZED_NAME_MMR_WINNER = "mmrWinner";
  @SerializedName(SERIALIZED_NAME_MMR_WINNER)
  @javax.annotation.Nullable
  private Integer mmrWinner;

  public static final String SERIALIZED_NAME_MMR_LOOSER = "mmrLooser";
  @SerializedName(SERIALIZED_NAME_MMR_LOOSER)
  @javax.annotation.Nullable
  private Integer mmrLooser;

  public static final String SERIALIZED_NAME_WINNER_HELPERS = "winnerHelpers";
  @SerializedName(SERIALIZED_NAME_WINNER_HELPERS)
  @javax.annotation.Nullable
  private List<String> winnerHelpers = new ArrayList<>();

  public static final String SERIALIZED_NAME_LOOSER_HELPERS = "looserHelpers";
  @SerializedName(SERIALIZED_NAME_LOOSER_HELPERS)
  @javax.annotation.Nullable
  private List<String> looserHelpers = new ArrayList<>();

  public WarAssault() {
  }

  public WarAssault startAt(@javax.annotation.Nullable Long startAt) {
    this.startAt = startAt;
    return this;
  }

  /**
   * Timestamp (ms) du début de l&#39;assaut
   * @return startAt
   */
  @javax.annotation.Nullable
  public Long getStartAt() {
    return startAt;
  }

  public void setStartAt(@javax.annotation.Nullable Long startAt) {
    this.startAt = startAt;
  }


  public WarAssault winner(@javax.annotation.Nullable String winner) {
    this.winner = winner;
    return this;
  }

  /**
   * Nom du pays vainqueur de l&#39;assaut
   * @return winner
   */
  @javax.annotation.Nullable
  public String getWinner() {
    return winner;
  }

  public void setWinner(@javax.annotation.Nullable String winner) {
    this.winner = winner;
  }


  public WarAssault looser(@javax.annotation.Nullable String looser) {
    this.looser = looser;
    return this;
  }

  /**
   * Nom du pays perdant de l&#39;assaut
   * @return looser
   */
  @javax.annotation.Nullable
  public String getLooser() {
    return looser;
  }

  public void setLooser(@javax.annotation.Nullable String looser) {
    this.looser = looser;
  }


  public WarAssault mmrWinner(@javax.annotation.Nullable Integer mmrWinner) {
    this.mmrWinner = mmrWinner;
    return this;
  }

  /**
   * MMR gagné par le pays vainqueur suite à sa victoire sur l&#39;assaut
   * @return mmrWinner
   */
  @javax.annotation.Nullable
  public Integer getMmrWinner() {
    return mmrWinner;
  }

  public void setMmrWinner(@javax.annotation.Nullable Integer mmrWinner) {
    this.mmrWinner = mmrWinner;
  }


  public WarAssault mmrLooser(@javax.annotation.Nullable Integer mmrLooser) {
    this.mmrLooser = mmrLooser;
    return this;
  }

  /**
   * MMR perdu par le pays perdant suite à sa défaite sur l&#39;assaut. Attention, pour signifier la perte, le nombre est négatif.
   * @return mmrLooser
   */
  @javax.annotation.Nullable
  public Integer getMmrLooser() {
    return mmrLooser;
  }

  public void setMmrLooser(@javax.annotation.Nullable Integer mmrLooser) {
    this.mmrLooser = mmrLooser;
  }


  public WarAssault winnerHelpers(@javax.annotation.Nullable List<String> winnerHelpers) {
    this.winnerHelpers = winnerHelpers;
    return this;
  }

  public WarAssault addWinnerHelpersItem(String winnerHelpersItem) {
    if (this.winnerHelpers == null) {
      this.winnerHelpers = new ArrayList<>();
    }
    this.winnerHelpers.add(winnerHelpersItem);
    return this;
  }

  /**
   * Liste des pays ayant aidé le vainqueur
   * @return winnerHelpers
   */
  @javax.annotation.Nullable
  public List<String> getWinnerHelpers() {
    return winnerHelpers;
  }

  public void setWinnerHelpers(@javax.annotation.Nullable List<String> winnerHelpers) {
    this.winnerHelpers = winnerHelpers;
  }


  public WarAssault looserHelpers(@javax.annotation.Nullable List<String> looserHelpers) {
    this.looserHelpers = looserHelpers;
    return this;
  }

  public WarAssault addLooserHelpersItem(String looserHelpersItem) {
    if (this.looserHelpers == null) {
      this.looserHelpers = new ArrayList<>();
    }
    this.looserHelpers.add(looserHelpersItem);
    return this;
  }

  /**
   * Liste des pays ayant aidé le perdant
   * @return looserHelpers
   */
  @javax.annotation.Nullable
  public List<String> getLooserHelpers() {
    return looserHelpers;
  }

  public void setLooserHelpers(@javax.annotation.Nullable List<String> looserHelpers) {
    this.looserHelpers = looserHelpers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WarAssault warAssault = (WarAssault) o;
    return Objects.equals(this.startAt, warAssault.startAt) &&
        Objects.equals(this.winner, warAssault.winner) &&
        Objects.equals(this.looser, warAssault.looser) &&
        Objects.equals(this.mmrWinner, warAssault.mmrWinner) &&
        Objects.equals(this.mmrLooser, warAssault.mmrLooser) &&
        Objects.equals(this.winnerHelpers, warAssault.winnerHelpers) &&
        Objects.equals(this.looserHelpers, warAssault.looserHelpers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startAt, winner, looser, mmrWinner, mmrLooser, winnerHelpers, looserHelpers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WarAssault {\n");
    sb.append("    startAt: ").append(toIndentedString(startAt)).append("\n");
    sb.append("    winner: ").append(toIndentedString(winner)).append("\n");
    sb.append("    looser: ").append(toIndentedString(looser)).append("\n");
    sb.append("    mmrWinner: ").append(toIndentedString(mmrWinner)).append("\n");
    sb.append("    mmrLooser: ").append(toIndentedString(mmrLooser)).append("\n");
    sb.append("    winnerHelpers: ").append(toIndentedString(winnerHelpers)).append("\n");
    sb.append("    looserHelpers: ").append(toIndentedString(looserHelpers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("startAt", "winner", "looser", "mmrWinner", "mmrLooser", "winnerHelpers", "looserHelpers"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WarAssault
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WarAssault.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WarAssault is not found in the empty JSON string", WarAssault.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WarAssault.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `WarAssault` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("winner") != null && !jsonObj.get("winner").isJsonNull()) && !jsonObj.get("winner").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `winner` to be a primitive type in the JSON string but got `%s`", jsonObj.get("winner").toString()));
      }
      if ((jsonObj.get("looser") != null && !jsonObj.get("looser").isJsonNull()) && !jsonObj.get("looser").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `looser` to be a primitive type in the JSON string but got `%s`", jsonObj.get("looser").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("winnerHelpers") != null && !jsonObj.get("winnerHelpers").isJsonNull() && !jsonObj.get("winnerHelpers").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `winnerHelpers` to be an array in the JSON string but got `%s`", jsonObj.get("winnerHelpers").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("looserHelpers") != null && !jsonObj.get("looserHelpers").isJsonNull() && !jsonObj.get("looserHelpers").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `looserHelpers` to be an array in the JSON string but got `%s`", jsonObj.get("looserHelpers").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WarAssault.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WarAssault' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WarAssault> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WarAssault.class));

       return (TypeAdapter<T>) new TypeAdapter<WarAssault>() {
           @Override
           public void write(JsonWriter out, WarAssault value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WarAssault read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WarAssault given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WarAssault
   * @throws IOException if the JSON string is invalid with respect to WarAssault
   */
  public static WarAssault fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WarAssault.class);
  }

  /**
   * Convert an instance of WarAssault to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

