/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import software.yoxo.client.model.WarAssault;
import software.yoxo.client.model.WarCondition;
import software.yoxo.client.model.WarMissile;
import software.yoxo.client.model.WarParticipant;
import software.yoxo.client.model.WarRewards;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * Détails d&#39;une guerre
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class WarEntry {
  public static final String SERIALIZED_NAME_WAR_ID = "warId";
  @SerializedName(SERIALIZED_NAME_WAR_ID)
  @javax.annotation.Nullable
  private String warId;

  public static final String SERIALIZED_NAME_WAR_DECLARED_AT = "warDeclaredAt";
  @SerializedName(SERIALIZED_NAME_WAR_DECLARED_AT)
  @javax.annotation.Nullable
  private Long warDeclaredAt;

  public static final String SERIALIZED_NAME_WAR_START_AT = "warStartAt";
  @SerializedName(SERIALIZED_NAME_WAR_START_AT)
  @javax.annotation.Nullable
  private Long warStartAt;

  public static final String SERIALIZED_NAME_WARS_INITIATED_BY = "warsInitiatedBy";
  @SerializedName(SERIALIZED_NAME_WARS_INITIATED_BY)
  @javax.annotation.Nullable
  private String warsInitiatedBy;

  /**
   * Raison de la déclaration de guerre
   */
  @JsonAdapter(ReasonEnum.Adapter.class)
  public enum ReasonEnum {
    KILL_WILDERNESS("KILL_WILDERNESS"),
    
    PROVOCATION("PROVOCATION"),
    
    TERRITORIAL_EXPANSION("TERRITORIAL_EXPANSION"),
    
    TREASON("TREASON"),
    
    INTRUSION("INTRUSION"),
    
    SCAM("SCAM"),
    
    TPKILL("TPKILL"),
    
    COLONY_IMDEPENDENCE("COLONY_IMDEPENDENCE"),
    
    COLONY_REFUSAL("COLONY_REFUSAL"),
    
    COLONY_PROTECTION("COLONY_PROTECTION"),
    
    COLONY_STEAL("COLONY_STEAL"),
    
    BUFFER_COUNTRY("BUFFER_COUNTRY"),
    
    UNDER_POWER("UNDER_POWER"),
    
    REPRISAL("REPRISAL"),
    
    FOLLOW_WAR("FOLLOW_WAR"),
    
    MMR500("MMR500"),
    
    EMPIRE_RIVALITY("EMPIRE_RIVALITY"),
    
    WAR_REVENGE("WAR_REVENGE"),
    
    BOMBING_ASSISTANCE("BOMBING_ASSISTANCE"),
    
    WARZONE_DOMINATION("WARZONE_DOMINATION"),
    
    PROTECTORAT("PROTECTORAT");

    private String value;

    ReasonEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ReasonEnum fromValue(String value) {
      for (ReasonEnum b : ReasonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ReasonEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ReasonEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ReasonEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ReasonEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ReasonEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  @javax.annotation.Nullable
  private ReasonEnum reason;

  public static final String SERIALIZED_NAME_TARGET = "target";
  @SerializedName(SERIALIZED_NAME_TARGET)
  @javax.annotation.Nullable
  private String target;

  /**
   * Grade du joueur ayant donné la raison de guerre (au moment de la raison de la guerre)
   */
  @JsonAdapter(TargetGradeEnum.Adapter.class)
  public enum TargetGradeEnum {
    RECRUIT("RECRUIT"),
    
    MEMBER("MEMBER"),
    
    OFFICER("OFFICER"),
    
    LEADER("LEADER");

    private String value;

    TargetGradeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TargetGradeEnum fromValue(String value) {
      for (TargetGradeEnum b : TargetGradeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TargetGradeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TargetGradeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TargetGradeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TargetGradeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TargetGradeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TARGET_GRADE = "targetGrade";
  @SerializedName(SERIALIZED_NAME_TARGET_GRADE)
  @javax.annotation.Nullable
  private TargetGradeEnum targetGrade;

  /**
   * Statut actuel de la guerre (ex: IN_PROGRESS, FINISHED)
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    IN_PROGRESS("IN_PROGRESS"),
    
    WAITING_VALIDATION("WAITING_VALIDATION"),
    
    WAITING_CONDITIONS_ATT("WAITING_CONDITIONS_ATT"),
    
    WAITING_CONDITIONS_DEF("WAITING_CONDITIONS_DEF"),
    
    WAITING_CONDITIONS_ATT_VALIDATION("WAITING_CONDITIONS_ATT_VALIDATION"),
    
    FINISHED("FINISHED"),
    
    REFUSED("REFUSED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_WINNER = "winner";
  @SerializedName(SERIALIZED_NAME_WINNER)
  @javax.annotation.Nullable
  private String winner;

  public static final String SERIALIZED_NAME_DAYS_BEFORE_MISSILE_POINT_RESET = "daysBeforeMissilePointReset";
  @SerializedName(SERIALIZED_NAME_DAYS_BEFORE_MISSILE_POINT_RESET)
  @javax.annotation.Nullable
  private Integer daysBeforeMissilePointReset;

  public static final String SERIALIZED_NAME_ATTACKER = "attacker";
  @SerializedName(SERIALIZED_NAME_ATTACKER)
  @javax.annotation.Nullable
  private WarParticipant attacker;

  public static final String SERIALIZED_NAME_DEFENDER = "defender";
  @SerializedName(SERIALIZED_NAME_DEFENDER)
  @javax.annotation.Nullable
  private WarParticipant defender;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  @javax.annotation.Nullable
  private WarCondition conditions;

  /**
   * Logique d&#39;application des conditions (AND: toutes requises, OR: une seule requise)
   */
  @JsonAdapter(ConditionTypeEnum.Adapter.class)
  public enum ConditionTypeEnum {
    OR("OR"),
    
    AND("AND");

    private String value;

    ConditionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ConditionTypeEnum fromValue(String value) {
      for (ConditionTypeEnum b : ConditionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ConditionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ConditionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ConditionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ConditionTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ConditionTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CONDITION_TYPE = "conditionType";
  @SerializedName(SERIALIZED_NAME_CONDITION_TYPE)
  @javax.annotation.Nullable
  private ConditionTypeEnum conditionType;

  public static final String SERIALIZED_NAME_REWARDS = "rewards";
  @SerializedName(SERIALIZED_NAME_REWARDS)
  @javax.annotation.Nullable
  private WarRewards rewards;

  public static final String SERIALIZED_NAME_ASSAULTS = "assaults";
  @SerializedName(SERIALIZED_NAME_ASSAULTS)
  @javax.annotation.Nullable
  private List<WarAssault> assaults = new ArrayList<>();

  public static final String SERIALIZED_NAME_MISSILES = "missiles";
  @SerializedName(SERIALIZED_NAME_MISSILES)
  @javax.annotation.Nullable
  private List<WarMissile> missiles = new ArrayList<>();

  public WarEntry() {
  }

  public WarEntry warId(@javax.annotation.Nullable String warId) {
    this.warId = warId;
    return this;
  }

  /**
   * Identifiant unique de la guerre permettant de lier avec les données des pays
   * @return warId
   */
  @javax.annotation.Nullable
  public String getWarId() {
    return warId;
  }

  public void setWarId(@javax.annotation.Nullable String warId) {
    this.warId = warId;
  }


  public WarEntry warDeclaredAt(@javax.annotation.Nullable Long warDeclaredAt) {
    this.warDeclaredAt = warDeclaredAt;
    return this;
  }

  /**
   * Timestamp (ms) de la déclaration de guerre
   * @return warDeclaredAt
   */
  @javax.annotation.Nullable
  public Long getWarDeclaredAt() {
    return warDeclaredAt;
  }

  public void setWarDeclaredAt(@javax.annotation.Nullable Long warDeclaredAt) {
    this.warDeclaredAt = warDeclaredAt;
  }


  public WarEntry warStartAt(@javax.annotation.Nullable Long warStartAt) {
    this.warStartAt = warStartAt;
    return this;
  }

  /**
   * Timestamp (ms) du début effectif de la guerre
   * @return warStartAt
   */
  @javax.annotation.Nullable
  public Long getWarStartAt() {
    return warStartAt;
  }

  public void setWarStartAt(@javax.annotation.Nullable Long warStartAt) {
    this.warStartAt = warStartAt;
  }


  public WarEntry warsInitiatedBy(@javax.annotation.Nullable String warsInitiatedBy) {
    this.warsInitiatedBy = warsInitiatedBy;
    return this;
  }

  /**
   * Joueur ayant initié la guerre via la commande /f enemy
   * @return warsInitiatedBy
   */
  @javax.annotation.Nullable
  public String getWarsInitiatedBy() {
    return warsInitiatedBy;
  }

  public void setWarsInitiatedBy(@javax.annotation.Nullable String warsInitiatedBy) {
    this.warsInitiatedBy = warsInitiatedBy;
  }


  public WarEntry reason(@javax.annotation.Nullable ReasonEnum reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Raison de la déclaration de guerre
   * @return reason
   */
  @javax.annotation.Nullable
  public ReasonEnum getReason() {
    return reason;
  }

  public void setReason(@javax.annotation.Nullable ReasonEnum reason) {
    this.reason = reason;
  }


  public WarEntry target(@javax.annotation.Nullable String target) {
    this.target = target;
    return this;
  }

  /**
   * Le pays ou joueur ayant donné la raison de guerre (peut être nul selon la raison)
   * @return target
   */
  @javax.annotation.Nullable
  public String getTarget() {
    return target;
  }

  public void setTarget(@javax.annotation.Nullable String target) {
    this.target = target;
  }


  public WarEntry targetGrade(@javax.annotation.Nullable TargetGradeEnum targetGrade) {
    this.targetGrade = targetGrade;
    return this;
  }

  /**
   * Grade du joueur ayant donné la raison de guerre (au moment de la raison de la guerre)
   * @return targetGrade
   */
  @javax.annotation.Nullable
  public TargetGradeEnum getTargetGrade() {
    return targetGrade;
  }

  public void setTargetGrade(@javax.annotation.Nullable TargetGradeEnum targetGrade) {
    this.targetGrade = targetGrade;
  }


  public WarEntry status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Statut actuel de la guerre (ex: IN_PROGRESS, FINISHED)
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public WarEntry winner(@javax.annotation.Nullable String winner) {
    this.winner = winner;
    return this;
  }

  /**
   * Le nom du pays vainqueur de la guerre (si terminée)
   * @return winner
   */
  @javax.annotation.Nullable
  public String getWinner() {
    return winner;
  }

  public void setWinner(@javax.annotation.Nullable String winner) {
    this.winner = winner;
  }


  public WarEntry daysBeforeMissilePointReset(@javax.annotation.Nullable Integer daysBeforeMissilePointReset) {
    this.daysBeforeMissilePointReset = daysBeforeMissilePointReset;
    return this;
  }

  /**
   * Nombre de jours restants avant la réinitialisation des points missile
   * @return daysBeforeMissilePointReset
   */
  @javax.annotation.Nullable
  public Integer getDaysBeforeMissilePointReset() {
    return daysBeforeMissilePointReset;
  }

  public void setDaysBeforeMissilePointReset(@javax.annotation.Nullable Integer daysBeforeMissilePointReset) {
    this.daysBeforeMissilePointReset = daysBeforeMissilePointReset;
  }


  public WarEntry attacker(@javax.annotation.Nullable WarParticipant attacker) {
    this.attacker = attacker;
    return this;
  }

  /**
   * Get attacker
   * @return attacker
   */
  @javax.annotation.Nullable
  public WarParticipant getAttacker() {
    return attacker;
  }

  public void setAttacker(@javax.annotation.Nullable WarParticipant attacker) {
    this.attacker = attacker;
  }


  public WarEntry defender(@javax.annotation.Nullable WarParticipant defender) {
    this.defender = defender;
    return this;
  }

  /**
   * Get defender
   * @return defender
   */
  @javax.annotation.Nullable
  public WarParticipant getDefender() {
    return defender;
  }

  public void setDefender(@javax.annotation.Nullable WarParticipant defender) {
    this.defender = defender;
  }


  public WarEntry conditions(@javax.annotation.Nullable WarCondition conditions) {
    this.conditions = conditions;
    return this;
  }

  /**
   * Get conditions
   * @return conditions
   */
  @javax.annotation.Nullable
  public WarCondition getConditions() {
    return conditions;
  }

  public void setConditions(@javax.annotation.Nullable WarCondition conditions) {
    this.conditions = conditions;
  }


  public WarEntry conditionType(@javax.annotation.Nullable ConditionTypeEnum conditionType) {
    this.conditionType = conditionType;
    return this;
  }

  /**
   * Logique d&#39;application des conditions (AND: toutes requises, OR: une seule requise)
   * @return conditionType
   */
  @javax.annotation.Nullable
  public ConditionTypeEnum getConditionType() {
    return conditionType;
  }

  public void setConditionType(@javax.annotation.Nullable ConditionTypeEnum conditionType) {
    this.conditionType = conditionType;
  }


  public WarEntry rewards(@javax.annotation.Nullable WarRewards rewards) {
    this.rewards = rewards;
    return this;
  }

  /**
   * Get rewards
   * @return rewards
   */
  @javax.annotation.Nullable
  public WarRewards getRewards() {
    return rewards;
  }

  public void setRewards(@javax.annotation.Nullable WarRewards rewards) {
    this.rewards = rewards;
  }


  public WarEntry assaults(@javax.annotation.Nullable List<WarAssault> assaults) {
    this.assaults = assaults;
    return this;
  }

  public WarEntry addAssaultsItem(WarAssault assaultsItem) {
    if (this.assaults == null) {
      this.assaults = new ArrayList<>();
    }
    this.assaults.add(assaultsItem);
    return this;
  }

  /**
   * Liste des assauts ayant eu lieu durant la guerre
   * @return assaults
   */
  @javax.annotation.Nullable
  public List<WarAssault> getAssaults() {
    return assaults;
  }

  public void setAssaults(@javax.annotation.Nullable List<WarAssault> assaults) {
    this.assaults = assaults;
  }


  public WarEntry missiles(@javax.annotation.Nullable List<WarMissile> missiles) {
    this.missiles = missiles;
    return this;
  }

  public WarEntry addMissilesItem(WarMissile missilesItem) {
    if (this.missiles == null) {
      this.missiles = new ArrayList<>();
    }
    this.missiles.add(missilesItem);
    return this;
  }

  /**
   * Liste des missiles lancés durant la guerre
   * @return missiles
   */
  @javax.annotation.Nullable
  public List<WarMissile> getMissiles() {
    return missiles;
  }

  public void setMissiles(@javax.annotation.Nullable List<WarMissile> missiles) {
    this.missiles = missiles;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WarEntry warEntry = (WarEntry) o;
    return Objects.equals(this.warId, warEntry.warId) &&
        Objects.equals(this.warDeclaredAt, warEntry.warDeclaredAt) &&
        Objects.equals(this.warStartAt, warEntry.warStartAt) &&
        Objects.equals(this.warsInitiatedBy, warEntry.warsInitiatedBy) &&
        Objects.equals(this.reason, warEntry.reason) &&
        Objects.equals(this.target, warEntry.target) &&
        Objects.equals(this.targetGrade, warEntry.targetGrade) &&
        Objects.equals(this.status, warEntry.status) &&
        Objects.equals(this.winner, warEntry.winner) &&
        Objects.equals(this.daysBeforeMissilePointReset, warEntry.daysBeforeMissilePointReset) &&
        Objects.equals(this.attacker, warEntry.attacker) &&
        Objects.equals(this.defender, warEntry.defender) &&
        Objects.equals(this.conditions, warEntry.conditions) &&
        Objects.equals(this.conditionType, warEntry.conditionType) &&
        Objects.equals(this.rewards, warEntry.rewards) &&
        Objects.equals(this.assaults, warEntry.assaults) &&
        Objects.equals(this.missiles, warEntry.missiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(warId, warDeclaredAt, warStartAt, warsInitiatedBy, reason, target, targetGrade, status, winner, daysBeforeMissilePointReset, attacker, defender, conditions, conditionType, rewards, assaults, missiles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WarEntry {\n");
    sb.append("    warId: ").append(toIndentedString(warId)).append("\n");
    sb.append("    warDeclaredAt: ").append(toIndentedString(warDeclaredAt)).append("\n");
    sb.append("    warStartAt: ").append(toIndentedString(warStartAt)).append("\n");
    sb.append("    warsInitiatedBy: ").append(toIndentedString(warsInitiatedBy)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    targetGrade: ").append(toIndentedString(targetGrade)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    winner: ").append(toIndentedString(winner)).append("\n");
    sb.append("    daysBeforeMissilePointReset: ").append(toIndentedString(daysBeforeMissilePointReset)).append("\n");
    sb.append("    attacker: ").append(toIndentedString(attacker)).append("\n");
    sb.append("    defender: ").append(toIndentedString(defender)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    conditionType: ").append(toIndentedString(conditionType)).append("\n");
    sb.append("    rewards: ").append(toIndentedString(rewards)).append("\n");
    sb.append("    assaults: ").append(toIndentedString(assaults)).append("\n");
    sb.append("    missiles: ").append(toIndentedString(missiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("warId", "warDeclaredAt", "warStartAt", "warsInitiatedBy", "reason", "target", "targetGrade", "status", "winner", "daysBeforeMissilePointReset", "attacker", "defender", "conditions", "conditionType", "rewards", "assaults", "missiles"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WarEntry
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WarEntry.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WarEntry is not found in the empty JSON string", WarEntry.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WarEntry.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `WarEntry` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("warId") != null && !jsonObj.get("warId").isJsonNull()) && !jsonObj.get("warId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `warId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("warId").toString()));
      }
      if ((jsonObj.get("warsInitiatedBy") != null && !jsonObj.get("warsInitiatedBy").isJsonNull()) && !jsonObj.get("warsInitiatedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `warsInitiatedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("warsInitiatedBy").toString()));
      }
      if ((jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) && !jsonObj.get("reason").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `reason` to be a primitive type in the JSON string but got `%s`", jsonObj.get("reason").toString()));
      }
      // validate the optional field `reason`
      if (jsonObj.get("reason") != null && !jsonObj.get("reason").isJsonNull()) {
        ReasonEnum.validateJsonElement(jsonObj.get("reason"));
      }
      if ((jsonObj.get("target") != null && !jsonObj.get("target").isJsonNull()) && !jsonObj.get("target").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `target` to be a primitive type in the JSON string but got `%s`", jsonObj.get("target").toString()));
      }
      if ((jsonObj.get("targetGrade") != null && !jsonObj.get("targetGrade").isJsonNull()) && !jsonObj.get("targetGrade").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `targetGrade` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetGrade").toString()));
      }
      // validate the optional field `targetGrade`
      if (jsonObj.get("targetGrade") != null && !jsonObj.get("targetGrade").isJsonNull()) {
        TargetGradeEnum.validateJsonElement(jsonObj.get("targetGrade"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("winner") != null && !jsonObj.get("winner").isJsonNull()) && !jsonObj.get("winner").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `winner` to be a primitive type in the JSON string but got `%s`", jsonObj.get("winner").toString()));
      }
      // validate the optional field `attacker`
      if (jsonObj.get("attacker") != null && !jsonObj.get("attacker").isJsonNull()) {
        WarParticipant.validateJsonElement(jsonObj.get("attacker"));
      }
      // validate the optional field `defender`
      if (jsonObj.get("defender") != null && !jsonObj.get("defender").isJsonNull()) {
        WarParticipant.validateJsonElement(jsonObj.get("defender"));
      }
      // validate the optional field `conditions`
      if (jsonObj.get("conditions") != null && !jsonObj.get("conditions").isJsonNull()) {
        WarCondition.validateJsonElement(jsonObj.get("conditions"));
      }
      if ((jsonObj.get("conditionType") != null && !jsonObj.get("conditionType").isJsonNull()) && !jsonObj.get("conditionType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `conditionType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("conditionType").toString()));
      }
      // validate the optional field `conditionType`
      if (jsonObj.get("conditionType") != null && !jsonObj.get("conditionType").isJsonNull()) {
        ConditionTypeEnum.validateJsonElement(jsonObj.get("conditionType"));
      }
      // validate the optional field `rewards`
      if (jsonObj.get("rewards") != null && !jsonObj.get("rewards").isJsonNull()) {
        WarRewards.validateJsonElement(jsonObj.get("rewards"));
      }
      if (jsonObj.get("assaults") != null && !jsonObj.get("assaults").isJsonNull()) {
        JsonArray jsonArrayassaults = jsonObj.getAsJsonArray("assaults");
        if (jsonArrayassaults != null) {
          // ensure the json data is an array
          if (!jsonObj.get("assaults").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `assaults` to be an array in the JSON string but got `%s`", jsonObj.get("assaults").toString()));
          }

          // validate the optional field `assaults` (array)
          for (int i = 0; i < jsonArrayassaults.size(); i++) {
            WarAssault.validateJsonElement(jsonArrayassaults.get(i));
          };
        }
      }
      if (jsonObj.get("missiles") != null && !jsonObj.get("missiles").isJsonNull()) {
        JsonArray jsonArraymissiles = jsonObj.getAsJsonArray("missiles");
        if (jsonArraymissiles != null) {
          // ensure the json data is an array
          if (!jsonObj.get("missiles").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `missiles` to be an array in the JSON string but got `%s`", jsonObj.get("missiles").toString()));
          }

          // validate the optional field `missiles` (array)
          for (int i = 0; i < jsonArraymissiles.size(); i++) {
            WarMissile.validateJsonElement(jsonArraymissiles.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WarEntry.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WarEntry' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WarEntry> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WarEntry.class));

       return (TypeAdapter<T>) new TypeAdapter<WarEntry>() {
           @Override
           public void write(JsonWriter out, WarEntry value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WarEntry read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WarEntry given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WarEntry
   * @throws IOException if the JSON string is invalid with respect to WarEntry
   */
  public static WarEntry fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WarEntry.class);
  }

  /**
   * Convert an instance of WarEntry to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

