/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import software.yoxo.client.model.WarCondition;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import software.yoxo.client.invoker.JSON;

/**
 * Détails d&#39;un pays participant à la guerre
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class WarParticipant {
  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nullable
  private String country;

  public static final String SERIALIZED_NAME_REMAINING_MISSILES_POINTS = "remainingMissilesPoints";
  @SerializedName(SERIALIZED_NAME_REMAINING_MISSILES_POINTS)
  @javax.annotation.Nullable
  private Integer remainingMissilesPoints;

  public static final String SERIALIZED_NAME_INACTIVITY = "inactivity";
  @SerializedName(SERIALIZED_NAME_INACTIVITY)
  @javax.annotation.Nullable
  private Integer inactivity;

  public static final String SERIALIZED_NAME_PROGRESS = "progress";
  @SerializedName(SERIALIZED_NAME_PROGRESS)
  @javax.annotation.Nullable
  private Double progress;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  @javax.annotation.Nullable
  private WarCondition condition;

  public WarParticipant() {
  }

  public WarParticipant country(@javax.annotation.Nullable String country) {
    this.country = country;
    return this;
  }

  /**
   * Nom du pays participant
   * @return country
   */
  @javax.annotation.Nullable
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }


  public WarParticipant remainingMissilesPoints(@javax.annotation.Nullable Integer remainingMissilesPoints) {
    this.remainingMissilesPoints = remainingMissilesPoints;
    return this;
  }

  /**
   * Points de missile restants utilisables par le pays
   * @return remainingMissilesPoints
   */
  @javax.annotation.Nullable
  public Integer getRemainingMissilesPoints() {
    return remainingMissilesPoints;
  }

  public void setRemainingMissilesPoints(@javax.annotation.Nullable Integer remainingMissilesPoints) {
    this.remainingMissilesPoints = remainingMissilesPoints;
  }


  public WarParticipant inactivity(@javax.annotation.Nullable Integer inactivity) {
    this.inactivity = inactivity;
    return this;
  }

  /**
   * Pourcentage d&#39;inactivité du pays. Augmente de 3% si les critères de connexion ne sont pas remplis pendant 2h
   * @return inactivity
   */
  @javax.annotation.Nullable
  public Integer getInactivity() {
    return inactivity;
  }

  public void setInactivity(@javax.annotation.Nullable Integer inactivity) {
    this.inactivity = inactivity;
  }


  public WarParticipant progress(@javax.annotation.Nullable Double progress) {
    this.progress = progress;
    return this;
  }

  /**
   * Pourcentage de progression vers la validation des conditions de victoire (0-100%). À 100%, le pays gagne
   * @return progress
   */
  @javax.annotation.Nullable
  public Double getProgress() {
    return progress;
  }

  public void setProgress(@javax.annotation.Nullable Double progress) {
    this.progress = progress;
  }


  public WarParticipant condition(@javax.annotation.Nullable WarCondition condition) {
    this.condition = condition;
    return this;
  }

  /**
   * Get condition
   * @return condition
   */
  @javax.annotation.Nullable
  public WarCondition getCondition() {
    return condition;
  }

  public void setCondition(@javax.annotation.Nullable WarCondition condition) {
    this.condition = condition;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WarParticipant warParticipant = (WarParticipant) o;
    return Objects.equals(this.country, warParticipant.country) &&
        Objects.equals(this.remainingMissilesPoints, warParticipant.remainingMissilesPoints) &&
        Objects.equals(this.inactivity, warParticipant.inactivity) &&
        Objects.equals(this.progress, warParticipant.progress) &&
        Objects.equals(this.condition, warParticipant.condition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, remainingMissilesPoints, inactivity, progress, condition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WarParticipant {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    remainingMissilesPoints: ").append(toIndentedString(remainingMissilesPoints)).append("\n");
    sb.append("    inactivity: ").append(toIndentedString(inactivity)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("country", "remainingMissilesPoints", "inactivity", "progress", "condition"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WarParticipant
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WarParticipant.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in WarParticipant is not found in the empty JSON string", WarParticipant.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WarParticipant.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `WarParticipant` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("country") != null && !jsonObj.get("country").isJsonNull()) && !jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      // validate the optional field `condition`
      if (jsonObj.get("condition") != null && !jsonObj.get("condition").isJsonNull()) {
        WarCondition.validateJsonElement(jsonObj.get("condition"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WarParticipant.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WarParticipant' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WarParticipant> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WarParticipant.class));

       return (TypeAdapter<T>) new TypeAdapter<WarParticipant>() {
           @Override
           public void write(JsonWriter out, WarParticipant value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WarParticipant read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WarParticipant given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WarParticipant
   * @throws IOException if the JSON string is invalid with respect to WarParticipant
   */
  public static WarParticipant fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WarParticipant.class);
  }

  /**
   * Convert an instance of WarParticipant to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

