# coding: utf-8

"""
    Yoxo API Server

    API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from yoxo-api_client.models.country import Country

class TestCountry(unittest.TestCase):
    """Country unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Country:
        """Test Country
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Country`
        """
        model = Country()
        if include_optional:
            return Country(
                data = [
                    yoxo-api_client.models.country_entry.CountryEntry(
                        name = 'France', 
                        description = '', 
                        motd = '', 
                        entry_msg = '', 
                        age = 56, 
                        count_members = 56, 
                        count_new_members = 56, 
                        fhome_coord = yoxo-api_client.models.country_coordinates.CountryCoordinates(
                            x = 56, 
                            z = 56, ), 
                        level = 56, 
                        progress = 56, 
                        notations_position = 56, 
                        tags = [
                            ''
                            ], 
                        discord = '', 
                        alliance_name = '', 
                        mmr = 56, 
                        claims = 56, 
                        power = 56, 
                        max_power = 56, 
                        powerboost_fixed = 56, 
                        powerboost_warzone = 56, 
                        powerboost_unesco = 56, 
                        powerboost_new_member = 56, 
                        powerboost_malus_assault = 56, 
                        flag = '', 
                        leader = '', 
                        officers = [
                            ''
                            ], 
                        members = [
                            ''
                            ], 
                        recruits = [
                            ''
                            ], 
                        new_members = [
                            yoxo-api_client.models.new_member_entry.NewMemberEntry(
                                pseudo = '', 
                                played_time = 56, 
                                reward_power = 56, 
                                reward_power_max = 56, 
                                reward_money = 56, 
                                reward_money_max = 56, 
                                step = 56, )
                            ], 
                        researches_level = yoxo-api_client.models.researches_entry.ResearchesEntry(
                            general = 56, 
                            resource = 56, 
                            military = 56, 
                            industry = 56, 
                            technology = 56, ), 
                        wars = [
                            ''
                            ], 
                        bank = yoxo-api_client.models.country_bank_entry.CountryBankEntry(
                            balance = 56, 
                            owners = [
                                ''
                                ], 
                            logs = [
                                yoxo-api_client.models.bank_log_entry.BankLogEntry(
                                    amount = 1.337, 
                                    timestamp = 56, 
                                    pseudo = '', )
                                ], ), 
                        actions = yoxo-api_client.models.country_actions_entry.CountryActionsEntry(
                            total_dividendes = 1.337, 
                            available_actions = 56, 
                            action_price = 56, 
                            dividendes_classement = [
                                yoxo-api_client.models.dividende_classement_entry.DividendeClassementEntry(
                                    pays = '', 
                                    montant = 1.337, )
                                ], 
                            dividendes_history = [
                                yoxo-api_client.models.dividende_history_entry.DividendeHistoryEntry(
                                    pays = '', 
                                    montant = 1.337, 
                                    timestamp = 56, )
                                ], ), 
                        settings = yoxo-api_client.models.country_settings_entry.CountrySettingsEntry(
                            invitation_needed = True, 
                            recruitment_open = True, 
                            do_kick_recruit_war_reason = True, 
                            do_kick_member_negative_power = True, 
                            permissions = [
                                yoxo-api_client.models.permission_entry.PermissionEntry(
                                    name = '', 
                                    description = '', 
                                    leader = True, 
                                    officer = True, 
                                    member = True, 
                                    recruit = True, 
                                    ally = True, 
                                    neutral = True, 
                                    enemy = True, )
                                ], ), 
                        empire = True, 
                        referent = True, 
                        top_warzone = True, 
                        restrict_assault = True, 
                        restrict_missile = True, )
                    ],
                metadata = yoxo-api_client.models.metadata.Metadata(
                    data_type = 'example', 
                    server = 'red', 
                    timestamp = 1760939974755, 
                    date = '2025-10-21', 
                    source = 's3://yoxo-history/example/2025-10-21_red_example.json.xz', 
                    cache_source = 'L1', 
                    execution_time_ms = 210, 
                    total_count = 50, 
                    filtered_count = 42, 
                    current_page = 1, 
                    page_size = 20, 
                    total_pages = 3, )
            )
        else:
            return Country(
        )
        """

    def testCountry(self):
        """Test Country"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
