# coding: utf-8

"""
    Yoxo API Server

    API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from yoxo_client.models.research_config import ResearchConfig

class TestResearchConfig(unittest.TestCase):
    """ResearchConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResearchConfig:
        """Test ResearchConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResearchConfig`
        """
        model = ResearchConfig()
        if include_optional:
            return ResearchConfig(
                data = {
                    'key' : yoxo_client.models.research_config_entry.ResearchConfigEntry(
                        name = 'Général', 
                        max_level = 15, 
                        description = 'Le domaine de recherche 'Général' permet de débloquer des fonctionnalités générales pour votre pays.', 
                        levels = [
                            yoxo_client.models.research_level_entry.ResearchLevelEntry(
                                level = 2, 
                                duration = 15, 
                                conditions = ["players#5","claims#15","has_motd"], 
                                rewards = ["30 membres max","10 relations max","3 officiers max"], )
                            ], )
                    },
                metadata = yoxo_client.models.metadata.Metadata(
                    data_type = 'example', 
                    server = 'red', 
                    timestamp = 1760939974755, 
                    date = '2025-10-21', 
                    source = 's3://yoxo-history/example/2025-10-21_red_example.json.xz', 
                    cache_source = 'L1', 
                    execution_time_ms = 210, 
                    total_count = 50, 
                    filtered_count = 42, 
                    current_page = 1, 
                    page_size = 20, 
                    total_pages = 3, )
            )
        else:
            return ResearchConfig(
        )
        """

    def testResearchConfig(self):
        """Test ResearchConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
