# coding: utf-8

"""
    Yoxo API Server

    API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from yoxo_api_client.models.alliance_entry import AllianceEntry

class TestAllianceEntry(unittest.TestCase):
    """AllianceEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AllianceEntry:
        """Test AllianceEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AllianceEntry`
        """
        model = AllianceEntry()
        if include_optional:
            return AllianceEntry(
                name = 'Poufsouffle',
                description = '',
                created_at = 1764342680849,
                color = '#FDC700',
                tags = ["PVP","FARMER"],
                discord = '',
                youtube = '',
                rules = '',
                banner_url = '',
                blazon = '',
                ranking = 1,
                prestige_points = 6980,
                station_module_count = 5,
                country_count = 7,
                leaders = ["EmpireMongol","Touva","Grece"],
                members = ["Papouasie","Brésil"],
                protectorats = ["France","Italie"],
                claims = 642,
                count_members = 176,
                taxes = yoxo_api_client.models.alliance_taxes.AllianceTaxes(
                    hdv_tax = 0.1, 
                    weekly_salary = 500, 
                    station_ticket = 1000, 
                    notation_tax = 10, 
                    join_tax = 50000, 
                    moon_teleport_cost = 250, 
                    fuel_cost = 100, ),
                modules = [
                    yoxo_api_client.models.alliance_module.AllianceModule(
                        id = 'generator', 
                        direction = 'NORTH', 
                        coordinates = yoxo_api_client.models.alliance_module_coordinates.AllianceModuleCoordinates(
                            x = 56, 
                            z = 56, ), 
                        name = 'Générateur électrique', 
                        description = '', )
                    ],
                bank = yoxo_api_client.models.alliance_bank.AllianceBank(
                    current_account_balance = 5000, 
                    blocked_account_balance = 125000, ),
                votes_history = [
                    yoxo_api_client.models.alliance_vote_history.AllianceVoteHistory(
                        type = 'OTHER_COUNTRY_JOIN_ALLIANCE', 
                        initiator = 'Romaindu35', 
                        initiator_country = 'EmpireMongol', 
                        timestamp = 1771364198349, 
                        message = 'Adhésion d'un pays', 
                        old_value = '', 
                        new_value = '', 
                        target_country = 'Papouasie', 
                        yes_votes = 3, 
                        no_votes = 1, )
                    ],
                relations = [
                    yoxo_api_client.models.alliance_relation.AllianceRelation(
                        name = 'Serdaigle', 
                        relation = 'neutral', 
                        surcharge_value_from = 1, 
                        has_embargo_from = True, 
                        surcharge_value_to = 5, 
                        has_embargo_to = False, )
                    ],
                prime_boost = yoxo_api_client.models.alliance_prime_boost.AlliancePrimeBoost(
                    has_boost_active = False, 
                    boost_percent = 8, 
                    boost_points = 27, 
                    prime_boosters = [
                        yoxo_api_client.models.alliance_prime_booster.AlliancePrimeBooster(
                            username = 'Romaindu35', 
                            boost_type = 'PREMIUM', 
                            boost_value = 1, )
                        ], ),
                open = True
            )
        else:
            return AllianceEntry(
        )
        """

    def testAllianceEntry(self):
        """Test AllianceEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
