# coding: utf-8

"""
    Yoxo API Server

    API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CerealGlobalMarketEntry(BaseModel):
    """
    Données du marché global des céréales.
    """ # noqa: E501
    prices_texture: Optional[StrictStr] = Field(default=None, description="Le graphique de l'évolution des prix des céréales au cours des 7 derniers jours au format base64.", alias="pricesTexture")
    sales_texture: Optional[StrictStr] = Field(default=None, description="Le graphique des ventes des différents céréales au cours des 7 derniers jours au format base64.", alias="salesTexture")
    stocks_texture: Optional[StrictStr] = Field(default=None, description="Le graphique de l'évolution des stocks des différents céréales au cours des 7 derniers jours au format base64.", alias="stocksTexture")
    prices_history: Optional[Dict[str, Dict[str, Union[StrictFloat, StrictInt]]]] = Field(default=None, description="L'historique des prix des différentes céréales sur le marché global au cours des 7 derniers jours.", alias="pricesHistory")
    sales_history: Optional[Dict[str, Dict[str, Union[StrictFloat, StrictInt]]]] = Field(default=None, description="L'historique des ventes des différentes céréales sur le marché global au cours des 7 derniers jours.", alias="salesHistory")
    stocks_history: Optional[Dict[str, Dict[str, Union[StrictFloat, StrictInt]]]] = Field(default=None, description="L'historique des stocks des différentes céréales sur le marché global au cours des 7 derniers jours.", alias="stocksHistory")
    cereals_price: Optional[Dict[str, StrictInt]] = Field(default=None, description="Les prix actuels des différentes céréales disponibles sur le marché global.", alias="cerealsPrice")
    __properties: ClassVar[List[str]] = ["pricesTexture", "salesTexture", "stocksTexture", "pricesHistory", "salesHistory", "stocksHistory", "cerealsPrice"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CerealGlobalMarketEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CerealGlobalMarketEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pricesTexture": obj.get("pricesTexture"),
            "salesTexture": obj.get("salesTexture"),
            "stocksTexture": obj.get("stocksTexture"),
            "pricesHistory": obj.get("pricesHistory"),
            "salesHistory": obj.get("salesHistory"),
            "stocksHistory": obj.get("stocksHistory"),
            "cerealsPrice": obj.get("cerealsPrice")
        })
        return _obj


