# coding: utf-8

"""
    Yoxo API Server

    API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from yoxo-api_client.models.enterprise_basic import EnterpriseBasic
from yoxo-api_client.models.enterprise_bet import EnterpriseBet
from yoxo-api_client.models.enterprise_casino import EnterpriseCasino
from yoxo-api_client.models.enterprise_electric import EnterpriseElectric
from yoxo-api_client.models.enterprise_farm import EnterpriseFarm
from yoxo-api_client.models.enterprise_petrol import EnterprisePetrol
from yoxo-api_client.models.enterprise_real_estate import EnterpriseRealEstate
from yoxo-api_client.models.enterprise_trader import EnterpriseTrader
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

ENTERPRISEENTRY_ONE_OF_SCHEMAS = ["EnterpriseBasic", "EnterpriseBet", "EnterpriseCasino", "EnterpriseElectric", "EnterpriseFarm", "EnterprisePetrol", "EnterpriseRealEstate", "EnterpriseTrader"]

class EnterpriseEntry(BaseModel):
    """
    Données d'une entreprise (différentes versions selon le type)
    """
    # data type: EnterpriseBet
    oneof_schema_1_validator: Optional[EnterpriseBet] = None
    # data type: EnterpriseCasino
    oneof_schema_2_validator: Optional[EnterpriseCasino] = None
    # data type: EnterpriseElectric
    oneof_schema_3_validator: Optional[EnterpriseElectric] = None
    # data type: EnterpriseFarm
    oneof_schema_4_validator: Optional[EnterpriseFarm] = None
    # data type: EnterpriseRealEstate
    oneof_schema_5_validator: Optional[EnterpriseRealEstate] = None
    # data type: EnterprisePetrol
    oneof_schema_6_validator: Optional[EnterprisePetrol] = None
    # data type: EnterpriseTrader
    oneof_schema_7_validator: Optional[EnterpriseTrader] = None
    # data type: EnterpriseBasic
    oneof_schema_8_validator: Optional[EnterpriseBasic] = None
    actual_instance: Optional[Union[EnterpriseBasic, EnterpriseBet, EnterpriseCasino, EnterpriseElectric, EnterpriseFarm, EnterprisePetrol, EnterpriseRealEstate, EnterpriseTrader]] = None
    one_of_schemas: Set[str] = { "EnterpriseBasic", "EnterpriseBet", "EnterpriseCasino", "EnterpriseElectric", "EnterpriseFarm", "EnterprisePetrol", "EnterpriseRealEstate", "EnterpriseTrader" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = EnterpriseEntry.model_construct()
        error_messages = []
        match = 0
        # validate data type: EnterpriseBet
        if not isinstance(v, EnterpriseBet):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EnterpriseBet`")
        else:
            match += 1
        # validate data type: EnterpriseCasino
        if not isinstance(v, EnterpriseCasino):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EnterpriseCasino`")
        else:
            match += 1
        # validate data type: EnterpriseElectric
        if not isinstance(v, EnterpriseElectric):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EnterpriseElectric`")
        else:
            match += 1
        # validate data type: EnterpriseFarm
        if not isinstance(v, EnterpriseFarm):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EnterpriseFarm`")
        else:
            match += 1
        # validate data type: EnterpriseRealEstate
        if not isinstance(v, EnterpriseRealEstate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EnterpriseRealEstate`")
        else:
            match += 1
        # validate data type: EnterprisePetrol
        if not isinstance(v, EnterprisePetrol):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EnterprisePetrol`")
        else:
            match += 1
        # validate data type: EnterpriseTrader
        if not isinstance(v, EnterpriseTrader):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EnterpriseTrader`")
        else:
            match += 1
        # validate data type: EnterpriseBasic
        if not isinstance(v, EnterpriseBasic):
            error_messages.append(f"Error! Input type `{type(v)}` is not `EnterpriseBasic`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in EnterpriseEntry with oneOf schemas: EnterpriseBasic, EnterpriseBet, EnterpriseCasino, EnterpriseElectric, EnterpriseFarm, EnterprisePetrol, EnterpriseRealEstate, EnterpriseTrader. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in EnterpriseEntry with oneOf schemas: EnterpriseBasic, EnterpriseBet, EnterpriseCasino, EnterpriseElectric, EnterpriseFarm, EnterprisePetrol, EnterpriseRealEstate, EnterpriseTrader. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into EnterpriseBet
        try:
            instance.actual_instance = EnterpriseBet.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EnterpriseCasino
        try:
            instance.actual_instance = EnterpriseCasino.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EnterpriseElectric
        try:
            instance.actual_instance = EnterpriseElectric.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EnterpriseFarm
        try:
            instance.actual_instance = EnterpriseFarm.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EnterpriseRealEstate
        try:
            instance.actual_instance = EnterpriseRealEstate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EnterprisePetrol
        try:
            instance.actual_instance = EnterprisePetrol.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EnterpriseTrader
        try:
            instance.actual_instance = EnterpriseTrader.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into EnterpriseBasic
        try:
            instance.actual_instance = EnterpriseBasic.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into EnterpriseEntry with oneOf schemas: EnterpriseBasic, EnterpriseBet, EnterpriseCasino, EnterpriseElectric, EnterpriseFarm, EnterprisePetrol, EnterpriseRealEstate, EnterpriseTrader. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into EnterpriseEntry with oneOf schemas: EnterpriseBasic, EnterpriseBet, EnterpriseCasino, EnterpriseElectric, EnterpriseFarm, EnterprisePetrol, EnterpriseRealEstate, EnterpriseTrader. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], EnterpriseBasic, EnterpriseBet, EnterpriseCasino, EnterpriseElectric, EnterpriseFarm, EnterprisePetrol, EnterpriseRealEstate, EnterpriseTrader]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


