/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.api;

import software.yoxo.client.invoker.ApiException;
import software.yoxo.client.model.CerealGlobalMarket;
import software.yoxo.client.model.Country;
import software.yoxo.client.model.Enterprise;
import software.yoxo.client.model.Halloween2025;
import java.time.LocalDate;
import software.yoxo.client.model.NoelMegagift2024;
import software.yoxo.client.model.NoelMegagift2025;
import software.yoxo.client.model.PlayerList;
import software.yoxo.client.model.PostQueryBody;
import software.yoxo.client.model.ResearchConfig;
import software.yoxo.client.model.ResearchServer;
import software.yoxo.client.model.Skill;
import software.yoxo.client.model.War;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiJavaApi
 */
@Disabled
public class ApiJavaApiTest {

    private final ApiJavaApi api = new ApiJavaApi();

    /**
     * Cereal Global Market
     *
     * Permet d&#39;obtenir les données du marché global des céréales pour un serveur spécifique à une date donnée.  Ces données incluent : - Les graphiques de l&#39;évolution des prix, des ventes et des stocks - L&#39;historique des prix, ventes et stocks par type de céréale - Les prix actuels des céréales  **Fréquence de mise à jour :** Les données sont actualisées tous les jours impairs du mois (environ une fois tous les 2 jours), généralement la nuit.  **Note :** Ces données représentent un objet unique (pas une liste), donc le filtrage et la pagination ne sont pas applicables. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCerealGlobalMarketTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        CerealGlobalMarket response = api.getCerealGlobalMarket(date, javaServer);
        // TODO: test validations
    }

    /**
     * Country
     *
     * Permet d&#39;obtenir la liste et les détails complets de tous les pays d&#39;un serveur à une date donnée (aucun filtrage possible). Il est possible de spécifier un pays dans l&#39;URL pour récupérer un pays spécifique.  **Données exposées :** - Informations générales (nom, description, niveau, power, claims...) - Relations (alliance, guerres) - Membres (liste, rôles, recrues) - Économie (banque, actions) - Paramètres et permissions  **Fréquence de mise à jour :** Les données sont actualisées tous les jours, généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCountryTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        Country response = api.getCountry(date, javaServer);
        // TODO: test validations
    }

    /**
     * Country
     *
     * Permet d&#39;obtenir la liste et les détails complets de tous les pays d&#39;un serveur à une date donnée (aucun filtrage possible). Il est possible de spécifier un pays dans l&#39;URL pour récupérer un pays spécifique.  **Données exposées :** - Informations générales (nom, description, niveau, power, claims...) - Relations (alliance, guerres) - Membres (liste, rôles, recrues) - Économie (banque, actions) - Paramètres et permissions  **Fréquence de mise à jour :** Les données sont actualisées tous les jours, généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCountry1Test() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        String country = null;
        Country response = api.getCountry1(date, javaServer, country);
        // TODO: test validations
    }

    /**
     * Enterprise
     *
     * Permet d&#39;obtenir la liste de toutes les entreprises sur un serveur à une date donnée. Chaque entreprise contient des champs communs (nom, propriétaire, employés, contrats) et des champs spécifiques selon son type (ex: historique des gains pour les casinos, production pour les centrales électriques). Il est possible de filtrer par nom d&#39;entreprise.  **Types d&#39;entreprises :** - Casino : Entreprises de casino - Electric : Entreprises électriques - Farm : Entreprises agricoles - Petrol : Entreprises pétrolières - Trader : Entreprises de trading - Bet : Entreprises de paris - RealEstate : Entreprises immobilières (location de parcelles) - Build, Engineer, Terraform, Journalist, PVP, Loan, Repair, Lawyer : Entreprises de services  **Fréquence de mise à jour :** Les données sont actualisées tous les lundis matin. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEnterprisesTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        String enterpriseType = null;
        Enterprise response = api.getEnterprises(date, javaServer, enterpriseType);
        // TODO: test validations
    }

    /**
     * Enterprise
     *
     * Permet d&#39;obtenir la liste de toutes les entreprises sur un serveur à une date donnée. Chaque entreprise contient des champs communs (nom, propriétaire, employés, contrats) et des champs spécifiques selon son type (ex: historique des gains pour les casinos, production pour les centrales électriques). Il est possible de filtrer par nom d&#39;entreprise.  **Types d&#39;entreprises :** - Casino : Entreprises de casino - Electric : Entreprises électriques - Farm : Entreprises agricoles - Petrol : Entreprises pétrolières - Trader : Entreprises de trading - Bet : Entreprises de paris - RealEstate : Entreprises immobilières (location de parcelles) - Build, Engineer, Terraform, Journalist, PVP, Loan, Repair, Lawyer : Entreprises de services  **Fréquence de mise à jour :** Les données sont actualisées tous les lundis matin. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getEnterprises1Test() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        String enterpriseName = null;
        String enterpriseType = null;
        Enterprise response = api.getEnterprises1(date, javaServer, enterpriseName, enterpriseType);
        // TODO: test validations
    }

    /**
     * Halloween 2025
     *
     * Permet d&#39;obtenir les statistiques des joueurs du top 50 de l&#39;événement Halloween 2025 \&quot;Demon&#39;s Return\&quot; à une date donnée (aucun filtrage possible). Seuls les joueurs du top 50 interserveur sont accessibles (limitation du serveur).  **À propos de l&#39;événement :** L&#39;événement \&quot;Demon&#39;s Return\&quot; est un événement global interserveur où l&#39;objectif est de collecter des âmes et tuer des démons pour empêcher l&#39;invasion démoniaque. Le classement est identique sur tous les serveurs puisqu&#39;il s&#39;agit d&#39;un événement global à NationsGlory.  **Fréquence de mise à jour :** Les données sont actualisées quotidiennement pendant toute la durée de l&#39;événement (du 21/10/2025 au 04/11/2025), généralement la nuit.  **Documentation :** Plus d&#39;informations sur l&#39;événement : https://wiki.nationsglory.fr/fr/article/halloween-2025-demons-return-1lfsu05/ 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getHalloween2025Test() throws ApiException {
        LocalDate date = null;
        Halloween2025 response = api.getHalloween2025(date);
        // TODO: test validations
    }

    /**
     * Noël Megagift 2024
     *
     * Permet d&#39;obtenir les données des tirages du Mega Cadeau de l&#39;événement \&quot;The Key Guardian\&quot; (Noël 2024).  **À propos de l&#39;événement :** L&#39;événement \&quot;The Key Guardian\&quot; est l&#39;événement de Noël 2024 où les joueurs doivent à récupérer 9 clés perdues pour assembler une Méga Clé et débloquer le Mega Cadeau. Chaque tirage du Mega Cadeau offre jusqu&#39;à 4 récompenses selon le nombre de joueurs présents (armes exclusives, plans rares, items légendaires, cosmétiques).  **Période de l&#39;événement :** Du 24/12/2024 au 12/01/2025  **Données exposées :** Chaque entrée représente un tirage individuel du Mega Gift par un joueur, avec les items obtenus et la date/heure du tirage. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNoelMegagift2024Test() throws ApiException {
        NoelMegagift2024 response = api.getNoelMegagift2024();
        // TODO: test validations
    }

    /**
     * Noël Megagift 2025
     *
     * Permet d&#39;obtenir les données des tirages du Mega Cadeau de l&#39;événement de Noël 2025.  **À propos de l&#39;événement :** Événement interserveur où les joueurs peuvent obtenir des récompenses exclusives via le Mega Cadeau. Plus d&#39;informations sur l&#39;événement : https://wiki.nationsglory.fr/fr/article/lile-du-pere-noel-rv8x0t/#2-le-mega-cadeau-recompense-ultime  **Période de l&#39;événement :** Du 14/12/2025 au 06/01/2026  **Données exposées :** Chaque entrée représente un tirage individuel du Mega cadeau par un joueur, avec les items obtenus et la date/heure du tirage.  **Fréquence de mise à jour :** Les données sont actualisées quotidiennement pendant toute la durée de l&#39;événement (du 14/12/2025 au 06/01/2026), généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getNoelMegagift2025Test() throws ApiException {
        LocalDate date = null;
        NoelMegagift2025 response = api.getNoelMegagift2025(date);
        // TODO: test validations
    }

    /**
     * Player List
     *
     * Permet d&#39;obtenir la liste des joueurs s&#39;étant connectés au moins une fois au cours des 14 derniers jours sur un serveur à une date donnée (aucun filtrage possible).  **Fréquence de mise à jour :** Les données sont actualisées quotidiennement, généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPlayerListTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        PlayerList response = api.getPlayerList(date, javaServer);
        // TODO: test validations
    }

    /**
     * Research Config
     *
     * Permet d&#39;obtenir la configuration globale de tous les domaines de recherche disponibles dans NationsGlory. Cette configuration est identique pour tous les serveurs et définit les niveaux, conditions et récompenses.  **Contenu de la configuration :** - Noms et descriptions des domaines de recherche - Niveaux maximum par domaine - Conditions requises par niveau - Récompenses obtenues par niveau - Durées de recherche  **Fréquence de mise à jour :** Les données sont actualisées tous les jours impairs du mois (environ une fois tous les 2 jours), généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResearchConfigTest() throws ApiException {
        LocalDate date = null;
        ResearchConfig response = api.getResearchConfig(date);
        // TODO: test validations
    }

    /**
     * Research Server
     *
     * Permet d&#39;obtenir les niveaux de recherche actuels de tous les pays d&#39;un serveur à une date donnée (sans filtrage).  **Données exposées :** - Niveaux actuels de recherche par domaine pour chaque pays - Dernière recherche complétée par chaque pays - Valeurs actuelles des conditions de recherche  **Fréquence de mise à jour :** Les données sont actualisées tous les jours impairs du mois (environ une fois tous les 2 jours), généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getResearchServerTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        ResearchServer response = api.getResearchServer(date, javaServer);
        // TODO: test validations
    }

    /**
     * Skill
     *
     * Permet d&#39;obtenir les compétences des joueurs présents dans au moins 1 top 50 compétences sur un serveur à une date donnée (aucun filtrage possible). Seuls les joueurs figurant dans le top 50 d&#39;au moins une compétence sur le serveur sont inclus pour éviter de surcharger les serveurs.  **Fréquence de mise à jour :** Les données sont actualisées tous les jours pairs du mois (environ une fois tous les 2 jours), généralement la nuit.  **Documentation :** Plus d&#39;informations sur les compétences/skills : https://wiki.nationsglory.fr/fr/article/les-competences-java-1shixp7/ 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSkillTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        Skill response = api.getSkill(date, javaServer);
        // TODO: test validations
    }

    /**
     * War
     *
     * Permet d&#39;obtenir la liste des guerres (en cours ou terminées) d&#39;un serveur à une date donnée. Il est possible de spécifier un warId dans l&#39;URL pour récupérer une guerre spécifique.  **Données exposées :** - Identifiant, dates (déclaration, début), raison - Participants (attaquant, défenseur) avec détails (pays, points missiles, progression...) - Conditions de victoire - Récompenses - Détails des assauts et missiles lancés  **Fréquence de mise à jour :** Les données sont actualisées quotidiennement, généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWarTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        War response = api.getWar(date, javaServer);
        // TODO: test validations
    }

    /**
     * War
     *
     * Permet d&#39;obtenir la liste des guerres (en cours ou terminées) d&#39;un serveur à une date donnée. Il est possible de spécifier un warId dans l&#39;URL pour récupérer une guerre spécifique.  **Données exposées :** - Identifiant, dates (déclaration, début), raison - Participants (attaquant, défenseur) avec détails (pays, points missiles, progression...) - Conditions de victoire - Récompenses - Détails des assauts et missiles lancés  **Fréquence de mise à jour :** Les données sont actualisées quotidiennement, généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWar1Test() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        String warId = null;
        War response = api.getWar1(date, javaServer, warId);
        // TODO: test validations
    }

    /**
     * Country
     *
     * Permet d&#39;obtenir la liste et les détails complets de tous les pays d&#39;un serveur à une date donnée (avec filtrage possible).  **Données exposées :** - Informations générales (nom, description, niveau, power, claims...) - Relations (alliance, guerres) - Membres (liste, rôles, recrues) - Économie (banque, actions) - Paramètres et permissions  **Fréquence de mise à jour :** Les données sont actualisées tous les jours, généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCountryTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        PostQueryBody postQueryBody = null;
        Country response = api.postCountry(date, javaServer, postQueryBody);
        // TODO: test validations
    }

    /**
     * Enterprise
     *
     * Permet d&#39;obtenir la liste de toutes les entreprises sur un serveur à une date donnée. Chaque entreprise contient des champs communs (nom, propriétaire, employés, contrats) et des champs spécifiques selon son type (ex: historique des gains pour les casinos, production pour les centrales électriques).  **Types d&#39;entreprises :** - Casino : Entreprises de casino - Electric : Entreprises électriques - Farm : Entreprises agricoles - Petrol : Entreprises pétrolières - Trader : Entreprises de trading - Bet : Entreprises de paris - RealEstate : Entreprises immobilières (location de parcelles) - Build, Engineer, Terraform, Journalist, PVP, Loan, Repair, Lawyer : Entreprises de services  **Fréquence de mise à jour :** Les données sont actualisées tous les lundis matin. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postEnterprisesTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        PostQueryBody postQueryBody = null;
        Enterprise response = api.postEnterprises(date, javaServer, postQueryBody);
        // TODO: test validations
    }

    /**
     * Halloween 2025
     *
     * Permet d&#39;obtenir les statistiques des joueurs du top 50 de l&#39;événement Halloween 2025 \&quot;Demon&#39;s Return\&quot; à une date donnée (avec filtrage possible). Seuls les joueurs du top 50 interserveur sont disponibles (limitation du serveur).  **À propos de l&#39;événement :** L&#39;événement \&quot;Demon&#39;s Return\&quot; est un événement global interserveur où l&#39;objectif est de collecter des âmes et tuer des démons pour empêcher l&#39;invasion démoniaque. Le classement est identique sur tous les serveurs puisqu&#39;il s&#39;agit d&#39;un événement global à NationsGlory.  **Fréquence de mise à jour :** Les données sont actualisées quotidiennement pendant toute la durée de l&#39;événement (du 21/10/2025 au 04/11/2025), généralement la nuit.  **Documentation :** Plus d&#39;informations sur l&#39;événement : https://wiki.nationsglory.fr/fr/article/halloween-2025-demons-return-1lfsu05/ 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postHalloween2025Test() throws ApiException {
        LocalDate date = null;
        PostQueryBody postQueryBody = null;
        Halloween2025 response = api.postHalloween2025(date, postQueryBody);
        // TODO: test validations
    }

    /**
     * Noël Megagift 2024
     *
     * Permet d&#39;obtenir les données des tirages du Mega Cadeau de l&#39;événement \&quot;The Key Guardian\&quot; (Noël 2024).  **À propos de l&#39;événement :** L&#39;événement \&quot;The Key Guardian\&quot; est l&#39;événement de Noël 2024 où les joueurs doivent à récupérer 9 clés perdues pour assembler une Méga Clé et débloquer le Mega Cadeau. Chaque tirage du Mega Cadeau offre jusqu&#39;à 4 récompenses selon le nombre de joueurs présents (armes exclusives, plans rares, items légendaires, cosmétiques).  **Période de l&#39;événement :** Du 24/12/2024 au 12/01/2025  **Données exposées :** Chaque entrée représente un tirage individuel du Mega Gift par un joueur, avec les items obtenus et la date/heure du tirage. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postNoelMegagift2024Test() throws ApiException {
        PostQueryBody postQueryBody = null;
        NoelMegagift2024 response = api.postNoelMegagift2024(postQueryBody);
        // TODO: test validations
    }

    /**
     * Noël Megagift 2025
     *
     * Permet d&#39;obtenir les données des tirages du Mega Cadeau de l&#39;événement de Noël 2025 (filtrage RSQL possible).  **À propos de l&#39;événement :** Événement interserveur où les joueurs peuvent obtenir des récompenses exclusives via le Mega Cadeau. Plus d&#39;informations sur l&#39;événement : https://wiki.nationsglory.fr/fr/article/lile-du-pere-noel-rv8x0t/#2-le-mega-cadeau-recompense-ultime  **Période de l&#39;événement :** Du 14/12/2025 au 06/01/2026  **Données exposées :** Chaque entrée représente un tirage individuel du Mega cadeau par un joueur, avec les items obtenus et la date/heure du tirage.  **Fréquence de mise à jour :** Les données sont actualisées quotidiennement pendant toute la durée de l&#39;événement (du 14/12/2025 au 06/01/2026), généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postNoelMegagift2025Test() throws ApiException {
        LocalDate date = null;
        PostQueryBody postQueryBody = null;
        NoelMegagift2025 response = api.postNoelMegagift2025(date, postQueryBody);
        // TODO: test validations
    }

    /**
     * Player List
     *
     * Permet d&#39;obtenir la liste des joueurs s&#39;étant connectés au moins une fois au cours des 14 derniers jours sur un serveur à une date donnée (avec filtrage possible).  **Fréquence de mise à jour :** Les données sont actualisées quotidiennement, généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postPlayerListTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        PostQueryBody postQueryBody = null;
        PlayerList response = api.postPlayerList(date, javaServer, postQueryBody);
        // TODO: test validations
    }

    /**
     * Research Server
     *
     * Permet d&#39;obtenir les niveaux de recherche actuels de tous les pays d&#39;un serveur à une date donnée (avec filtrage possible).  **Données exposées :** - Niveaux actuels de recherche par domaine pour chaque pays - Dernière recherche complétée par chaque pays - Valeurs actuelles des conditions de recherche  **Exemples de filtres RSQL :** - &#x60;country&#x3D;&#x3D;Papouasie&#x60; - Pays nommé exactement \&quot;Papouasie\&quot; - &#x60;country&#x3D;&#x3D;*Terre*&#x60; - Pays dont le nom contient \&quot;Terre\&quot; - &#x60;lastResearch.level&gt;3&#x60; - Pays dont la dernière recherche a atteint un niveau &gt; 3 - &#x60;lastResearch.domain&#x3D;&#x3D;militaire&#x60; - Pays dont la dernière recherche était dans le domaine militaire - &#x60;lastResearch.timestamp&gt;1735689600000&#x60; - Pays dont la dernière recherche a été complétée après cette date  **Fréquence de mise à jour :** Les données sont actualisées tous les jours pairs du mois (environ une fois tous les 2 jours), généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postResearchServerTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        PostQueryBody postQueryBody = null;
        ResearchServer response = api.postResearchServer(date, javaServer, postQueryBody);
        // TODO: test validations
    }

    /**
     * Skill
     *
     * Permet d&#39;obtenir les compétences des joueurs présents dans au moins 1 top 50 compétences sur un serveur à une date donnée (avec filtrage possible). Seuls les joueurs figurant dans le top 50 d&#39;au moins une compétence sur le serveur sont inclus pour éviter de surcharger les serveurs.  **Fréquence de mise à jour :** Les données sont actualisées tous les jours pairs du mois (environ une fois tous les 2 jours), généralement la nuit.  **Documentation :** Plus d&#39;informations sur les compétences/skills : https://wiki.nationsglory.fr/fr/article/les-competences-java-1shixp7/ 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postSkillTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        PostQueryBody postQueryBody = null;
        Skill response = api.postSkill(date, javaServer, postQueryBody);
        // TODO: test validations
    }

    /**
     * War
     *
     * Permet d&#39;obtenir la liste des guerres (en cours ou terminées) d&#39;un serveur à une date donnée (avec filtrage possible).  **Données exposées :** - Identifiant, dates (déclaration, début), raison - Participants (attaquant, défenseur) avec détails (pays, points missiles, progression...) - Conditions de victoire - Récompenses - Détails des assauts et missiles lancés  **Fréquence de mise à jour :** Les données sont actualisées quotidiennement, généralement la nuit. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postWarTest() throws ApiException {
        LocalDate date = null;
        String javaServer = null;
        PostQueryBody postQueryBody = null;
        War response = api.postWar(date, javaServer, postQueryBody);
        // TODO: test validations
    }

}
