/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ArchitectureEntry
 */
public class ArchitectureEntryTest {
    private final ArchitectureEntry model = new ArchitectureEntry();

    /**
     * Model tests for ArchitectureEntry
     */
    @Test
    public void testArchitectureEntry() {
        // TODO: test ArchitectureEntry
    }

    /**
     * Test the property 'terraforming'
     */
    @Test
    public void terraformingTest() {
        // TODO: test terraforming
    }

    /**
     * Test the property 'coherenceStyle'
     */
    @Test
    public void coherenceStyleTest() {
        // TODO: test coherenceStyle
    }

    /**
     * Test the property 'activiteRecente'
     */
    @Test
    public void activiteRecenteTest() {
        // TODO: test activiteRecente
    }

    /**
     * Test the property 'blocsCatalogue'
     */
    @Test
    public void blocsCatalogueTest() {
        // TODO: test blocsCatalogue
    }

    /**
     * Test the property 'trouMissiles'
     */
    @Test
    public void trouMissilesTest() {
        // TODO: test trouMissiles
    }

    /**
     * Test the property 'beauteGenerale'
     */
    @Test
    public void beauteGeneraleTest() {
        // TODO: test beauteGenerale
    }

    /**
     * Test the property 'habitabiliteMaison'
     */
    @Test
    public void habitabiliteMaisonTest() {
        // TODO: test habitabiliteMaison
    }

    /**
     * Test the property 'biomeCoherent'
     */
    @Test
    public void biomeCoherentTest() {
        // TODO: test biomeCoherent
    }

    /**
     * Test the property 'batimentsAbandonnes'
     */
    @Test
    public void batimentsAbandonnesTest() {
        // TODO: test batimentsAbandonnes
    }

    /**
     * Test the property 'utilisationSchematica'
     */
    @Test
    public void utilisationSchematicaTest() {
        // TODO: test utilisationSchematica
    }

    /**
     * Test the property 'coherenceLumieres'
     */
    @Test
    public void coherenceLumieresTest() {
        // TODO: test coherenceLumieres
    }

    /**
     * Test the property 'roleplayPays'
     */
    @Test
    public void roleplayPaysTest() {
        // TODO: test roleplayPays
    }

    /**
     * Test the property 'organics'
     */
    @Test
    public void organicsTest() {
        // TODO: test organics
    }

    /**
     * Test the property 'surfaceConstruite'
     */
    @Test
    public void surfaceConstruiteTest() {
        // TODO: test surfaceConstruite
    }

    /**
     * Test the property 'staff'
     */
    @Test
    public void staffTest() {
        // TODO: test staff
    }

}
