/*
 * Yoxo API Server
 * API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/_*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package software.yoxo.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import software.yoxo.client.model.ActionEntry;
import software.yoxo.client.model.DividendeClassementEntry;
import software.yoxo.client.model.DividendeHistoryEntry;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CountryActionsEntry
 */
public class CountryActionsEntryTest {
    private final CountryActionsEntry model = new CountryActionsEntry();

    /**
     * Model tests for CountryActionsEntry
     */
    @Test
    public void testCountryActionsEntry() {
        // TODO: test CountryActionsEntry
    }

    /**
     * Test the property 'totalDividendes'
     */
    @Test
    public void totalDividendesTest() {
        // TODO: test totalDividendes
    }

    /**
     * Test the property 'availableActions'
     */
    @Test
    public void availableActionsTest() {
        // TODO: test availableActions
    }

    /**
     * Test the property 'actionPrice'
     */
    @Test
    public void actionPriceTest() {
        // TODO: test actionPrice
    }

    /**
     * Test the property 'dividendesClassement'
     */
    @Test
    public void dividendesClassementTest() {
        // TODO: test dividendesClassement
    }

    /**
     * Test the property 'dividendesHistory'
     */
    @Test
    public void dividendesHistoryTest() {
        // TODO: test dividendesHistory
    }

    /**
     * Test the property 'actions'
     */
    @Test
    public void actionsTest() {
        // TODO: test actions
    }

}
