# coding: utf-8

# flake8: noqa

"""
    Yoxo API Server

    API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.1"

# Define package exports
__all__ = [
    "APIJavaApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ActionEntry",
    "BankLogEntry",
    "CerealGlobalMarket",
    "CerealGlobalMarketEntry",
    "Coords",
    "Country",
    "CountryActionsEntry",
    "CountryBankEntry",
    "CountryCoordinates",
    "CountryEntry",
    "CountryResearchEntry",
    "CountrySettingsEntry",
    "DividendeClassementEntry",
    "DividendeHistoryEntry",
    "Enterprise",
    "EnterpriseBank",
    "EnterpriseBankLog",
    "EnterpriseBase",
    "EnterpriseBasic",
    "EnterpriseBet",
    "EnterpriseBetItem",
    "EnterpriseCasino",
    "EnterpriseElectric",
    "EnterpriseEntry",
    "EnterpriseFarm",
    "EnterprisePermission",
    "EnterprisePetrol",
    "EnterpriseRealEstate",
    "EnterpriseTrader",
    "Halloween2025",
    "Halloween2025Entry",
    "LastResearchEntry",
    "Metadata",
    "NewMemberEntry",
    "NoelMegagift2024",
    "NoelMegagift2024Entry",
    "NoelMegagift2025",
    "NoelMegagift2025Entry",
    "Parcelle",
    "PermissionEntry",
    "PlayerList",
    "PlayerListEntry",
    "PostQueryBody",
    "ResearchConfig",
    "ResearchConfigEntry",
    "ResearchLevelEntry",
    "ResearchServer",
    "ResearchesEntry",
    "SettingLogEntry",
    "Skill",
    "SkillEntry",
    "War",
    "WarAssault",
    "WarCondition",
    "WarEntry",
    "WarMissile",
    "WarParticipant",
    "WarRewards",
]

# import apis into sdk package
from yoxo_client.api.api_java_api import APIJavaApi as APIJavaApi

# import ApiClient
from yoxo_client.api_response import ApiResponse as ApiResponse
from yoxo_client.api_client import ApiClient as ApiClient
from yoxo_client.configuration import Configuration as Configuration
from yoxo_client.exceptions import OpenApiException as OpenApiException
from yoxo_client.exceptions import ApiTypeError as ApiTypeError
from yoxo_client.exceptions import ApiValueError as ApiValueError
from yoxo_client.exceptions import ApiKeyError as ApiKeyError
from yoxo_client.exceptions import ApiAttributeError as ApiAttributeError
from yoxo_client.exceptions import ApiException as ApiException

# import models into sdk package
from yoxo_client.models.action_entry import ActionEntry as ActionEntry
from yoxo_client.models.bank_log_entry import BankLogEntry as BankLogEntry
from yoxo_client.models.cereal_global_market import CerealGlobalMarket as CerealGlobalMarket
from yoxo_client.models.cereal_global_market_entry import CerealGlobalMarketEntry as CerealGlobalMarketEntry
from yoxo_client.models.coords import Coords as Coords
from yoxo_client.models.country import Country as Country
from yoxo_client.models.country_actions_entry import CountryActionsEntry as CountryActionsEntry
from yoxo_client.models.country_bank_entry import CountryBankEntry as CountryBankEntry
from yoxo_client.models.country_coordinates import CountryCoordinates as CountryCoordinates
from yoxo_client.models.country_entry import CountryEntry as CountryEntry
from yoxo_client.models.country_research_entry import CountryResearchEntry as CountryResearchEntry
from yoxo_client.models.country_settings_entry import CountrySettingsEntry as CountrySettingsEntry
from yoxo_client.models.dividende_classement_entry import DividendeClassementEntry as DividendeClassementEntry
from yoxo_client.models.dividende_history_entry import DividendeHistoryEntry as DividendeHistoryEntry
from yoxo_client.models.enterprise import Enterprise as Enterprise
from yoxo_client.models.enterprise_bank import EnterpriseBank as EnterpriseBank
from yoxo_client.models.enterprise_bank_log import EnterpriseBankLog as EnterpriseBankLog
from yoxo_client.models.enterprise_base import EnterpriseBase as EnterpriseBase
from yoxo_client.models.enterprise_basic import EnterpriseBasic as EnterpriseBasic
from yoxo_client.models.enterprise_bet import EnterpriseBet as EnterpriseBet
from yoxo_client.models.enterprise_bet_item import EnterpriseBetItem as EnterpriseBetItem
from yoxo_client.models.enterprise_casino import EnterpriseCasino as EnterpriseCasino
from yoxo_client.models.enterprise_electric import EnterpriseElectric as EnterpriseElectric
from yoxo_client.models.enterprise_entry import EnterpriseEntry as EnterpriseEntry
from yoxo_client.models.enterprise_farm import EnterpriseFarm as EnterpriseFarm
from yoxo_client.models.enterprise_permission import EnterprisePermission as EnterprisePermission
from yoxo_client.models.enterprise_petrol import EnterprisePetrol as EnterprisePetrol
from yoxo_client.models.enterprise_real_estate import EnterpriseRealEstate as EnterpriseRealEstate
from yoxo_client.models.enterprise_trader import EnterpriseTrader as EnterpriseTrader
from yoxo_client.models.halloween2025 import Halloween2025 as Halloween2025
from yoxo_client.models.halloween2025_entry import Halloween2025Entry as Halloween2025Entry
from yoxo_client.models.last_research_entry import LastResearchEntry as LastResearchEntry
from yoxo_client.models.metadata import Metadata as Metadata
from yoxo_client.models.new_member_entry import NewMemberEntry as NewMemberEntry
from yoxo_client.models.noel_megagift2024 import NoelMegagift2024 as NoelMegagift2024
from yoxo_client.models.noel_megagift2024_entry import NoelMegagift2024Entry as NoelMegagift2024Entry
from yoxo_client.models.noel_megagift2025 import NoelMegagift2025 as NoelMegagift2025
from yoxo_client.models.noel_megagift2025_entry import NoelMegagift2025Entry as NoelMegagift2025Entry
from yoxo_client.models.parcelle import Parcelle as Parcelle
from yoxo_client.models.permission_entry import PermissionEntry as PermissionEntry
from yoxo_client.models.player_list import PlayerList as PlayerList
from yoxo_client.models.player_list_entry import PlayerListEntry as PlayerListEntry
from yoxo_client.models.post_query_body import PostQueryBody as PostQueryBody
from yoxo_client.models.research_config import ResearchConfig as ResearchConfig
from yoxo_client.models.research_config_entry import ResearchConfigEntry as ResearchConfigEntry
from yoxo_client.models.research_level_entry import ResearchLevelEntry as ResearchLevelEntry
from yoxo_client.models.research_server import ResearchServer as ResearchServer
from yoxo_client.models.researches_entry import ResearchesEntry as ResearchesEntry
from yoxo_client.models.setting_log_entry import SettingLogEntry as SettingLogEntry
from yoxo_client.models.skill import Skill as Skill
from yoxo_client.models.skill_entry import SkillEntry as SkillEntry
from yoxo_client.models.war import War as War
from yoxo_client.models.war_assault import WarAssault as WarAssault
from yoxo_client.models.war_condition import WarCondition as WarCondition
from yoxo_client.models.war_entry import WarEntry as WarEntry
from yoxo_client.models.war_missile import WarMissile as WarMissile
from yoxo_client.models.war_participant import WarParticipant as WarParticipant
from yoxo_client.models.war_rewards import WarRewards as WarRewards


from yoxo_client.client import YoxoClient
