# coding: utf-8

"""
    Yoxo API Server

    API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from yoxo_api_client.models.alliance_bank import AllianceBank
from yoxo_api_client.models.alliance_module import AllianceModule
from yoxo_api_client.models.alliance_prime_boost import AlliancePrimeBoost
from yoxo_api_client.models.alliance_relation import AllianceRelation
from yoxo_api_client.models.alliance_taxes import AllianceTaxes
from yoxo_api_client.models.alliance_vote_history import AllianceVoteHistory
from typing import Optional, Set
from typing_extensions import Self

class AllianceEntry(BaseModel):
    """
    Données d'une alliance
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, description="Le nom de l'alliance")
    description: Optional[StrictStr] = Field(default=None, description="La description de l'alliance")
    created_at: Optional[StrictInt] = Field(default=None, description="Le timestamp en ms à la date dont l'alliance a été créer", alias="createdAt")
    color: Optional[StrictStr] = Field(default=None, description="La couleur de l'alliance au format héxadécimale. La couleur représente l'alliance et est unique à l'échelle du serveur")
    tags: Optional[List[StrictStr]] = Field(default=None, description="La liste des tags de l'alliance")
    discord: Optional[StrictStr] = Field(default=None, description="Le lien menant au discord de l'alliance")
    youtube: Optional[StrictStr] = Field(default=None, description="Le lien menant à la chaine youtube de l'alliance")
    rules: Optional[StrictStr] = Field(default=None, description="Les règles de l'alliance")
    banner_url: Optional[StrictStr] = Field(default=None, description="L'url de la banière affiché sur la page de l'alliance", alias="bannerUrl")
    blazon: Optional[StrictStr] = Field(default=None, description="Le blazon représentant l'alliance. Image en base64, de dimension 78x78")
    ranking: Optional[StrictInt] = Field(default=None, description="Le classement de l'alliance sur le mois en cours. Calculé en fonction du nombre de points de prestiges")
    prestige_points: Optional[StrictInt] = Field(default=None, description="Les points de prestige de l'alliance. La documentation du prestige est consultable à l'adresse https://wiki.nationsglory.fr/fr/article/les-alliances-java-1ju6vju/#1-prestige-classement", alias="prestigePoints")
    station_module_count: Optional[StrictInt] = Field(default=None, description="Le nombre de module dans la station spatiale de l'alliance", alias="stationModuleCount")
    country_count: Optional[StrictInt] = Field(default=None, description="Le nombre de pays dans l'alliance", alias="countryCount")
    leaders: Optional[List[StrictStr]] = Field(default=None, description="La liste des pays leader de l'alliance")
    members: Optional[List[StrictStr]] = Field(default=None, description="La liste des pays membres de l'alliance")
    protectorats: Optional[List[StrictStr]] = Field(default=None, description="La liste des pays sous le statut de protectorat dans l'alliance")
    claims: Optional[StrictInt] = Field(default=None, description="Le nombre de claims cumulé des pays de l'alliance")
    count_members: Optional[StrictInt] = Field(default=None, description="Le nombre de membres cumulés des pays de l'alliance", alias="countMembers")
    taxes: Optional[AllianceTaxes] = None
    modules: Optional[List[AllianceModule]] = Field(default=None, description="Les modules construits dans la station spatiale")
    bank: Optional[AllianceBank] = None
    votes_history: Optional[List[AllianceVoteHistory]] = Field(default=None, description="L'historique des votes de l'alliance. Nécessite d'être membre de l'alliance pour y avoir accès", alias="votesHistory")
    relations: Optional[List[AllianceRelation]] = Field(default=None, description="Les relations avec les autres alliances")
    prime_boost: Optional[AlliancePrimeBoost] = Field(default=None, alias="primeBoost")
    open: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["name", "description", "createdAt", "color", "tags", "discord", "youtube", "rules", "bannerUrl", "blazon", "ranking", "prestigePoints", "stationModuleCount", "countryCount", "leaders", "members", "protectorats", "claims", "countMembers", "taxes", "modules", "bank", "votesHistory", "relations", "primeBoost", "open"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AllianceEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of taxes
        if self.taxes:
            _dict['taxes'] = self.taxes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in modules (list)
        _items = []
        if self.modules:
            for _item_modules in self.modules:
                if _item_modules:
                    _items.append(_item_modules.to_dict())
            _dict['modules'] = _items
        # override the default output from pydantic by calling `to_dict()` of bank
        if self.bank:
            _dict['bank'] = self.bank.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in votes_history (list)
        _items = []
        if self.votes_history:
            for _item_votes_history in self.votes_history:
                if _item_votes_history:
                    _items.append(_item_votes_history.to_dict())
            _dict['votesHistory'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in relations (list)
        _items = []
        if self.relations:
            for _item_relations in self.relations:
                if _item_relations:
                    _items.append(_item_relations.to_dict())
            _dict['relations'] = _items
        # override the default output from pydantic by calling `to_dict()` of prime_boost
        if self.prime_boost:
            _dict['primeBoost'] = self.prime_boost.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AllianceEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "createdAt": obj.get("createdAt"),
            "color": obj.get("color"),
            "tags": obj.get("tags"),
            "discord": obj.get("discord"),
            "youtube": obj.get("youtube"),
            "rules": obj.get("rules"),
            "bannerUrl": obj.get("bannerUrl"),
            "blazon": obj.get("blazon"),
            "ranking": obj.get("ranking"),
            "prestigePoints": obj.get("prestigePoints"),
            "stationModuleCount": obj.get("stationModuleCount"),
            "countryCount": obj.get("countryCount"),
            "leaders": obj.get("leaders"),
            "members": obj.get("members"),
            "protectorats": obj.get("protectorats"),
            "claims": obj.get("claims"),
            "countMembers": obj.get("countMembers"),
            "taxes": AllianceTaxes.from_dict(obj["taxes"]) if obj.get("taxes") is not None else None,
            "modules": [AllianceModule.from_dict(_item) for _item in obj["modules"]] if obj.get("modules") is not None else None,
            "bank": AllianceBank.from_dict(obj["bank"]) if obj.get("bank") is not None else None,
            "votesHistory": [AllianceVoteHistory.from_dict(_item) for _item in obj["votesHistory"]] if obj.get("votesHistory") is not None else None,
            "relations": [AllianceRelation.from_dict(_item) for _item in obj["relations"]] if obj.get("relations") is not None else None,
            "primeBoost": AlliancePrimeBoost.from_dict(obj["primeBoost"]) if obj.get("primeBoost") is not None else None,
            "open": obj.get("open")
        })
        return _obj


