# coding: utf-8

"""
    Yoxo API Server

    API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ArchitectureEntry(BaseModel):
    """
    ArchitectureEntry
    """ # noqa: E501
    terraforming: Optional[StrictInt] = Field(default=None, description="Terraforming (entre 0 et 2)")
    coherence_style: Optional[StrictInt] = Field(default=None, description="Cohérence du style (entre 0 et 2)", alias="coherenceStyle")
    activite_recente: Optional[StrictInt] = Field(default=None, description="Activité récente (entre 0 et 4)", alias="activiteRecente")
    blocs_catalogue: Optional[StrictInt] = Field(default=None, description="Utilisation de blocs du catalogue (entre 0 et 2)", alias="blocsCatalogue")
    trou_missiles: Optional[StrictInt] = Field(default=None, description="Présence de trous de missiles (entre 0 et -4)", alias="trouMissiles")
    beaute_generale: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Beauté générale du pays (entre 0 et 4)", alias="beauteGenerale")
    habitabilite_maison: Optional[StrictInt] = Field(default=None, description="Habitabilité des maisons (entre 0 et 2)", alias="habitabiliteMaison")
    biome_coherent: Optional[StrictInt] = Field(default=None, description="Cohérence avec le biome (entre 0 et 1)", alias="biomeCoherent")
    batiments_abandonnes: Optional[StrictInt] = Field(default=None, description="Absence de bâtiments abandonnés (1 si aucun, 0 sinon)", alias="batimentsAbandonnes")
    utilisation_schematica: Optional[StrictInt] = Field(default=None, description="Utilisation de schematica (0 si non, -1 si oui)", alias="utilisationSchematica")
    coherence_lumieres: Optional[StrictInt] = Field(default=None, description="Cohérence des lumières (entre 0 et 1)", alias="coherenceLumieres")
    roleplay_pays: Optional[StrictInt] = Field(default=None, description="Respect du roleplay du pays (entre 0 et 1)", alias="roleplayPays")
    organics: Optional[StrictInt] = Field(default=None, description="Présence d'organics (entre 0 et 1)")
    surface_construite: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Multiplicateur de surface construite (entre x0 et x2.0)", alias="surfaceConstruite")
    staff: Optional[StrictStr] = Field(default=None, description="Le username du staff qui a noté le pays")
    __properties: ClassVar[List[str]] = ["terraforming", "coherenceStyle", "activiteRecente", "blocsCatalogue", "trouMissiles", "beauteGenerale", "habitabiliteMaison", "biomeCoherent", "batimentsAbandonnes", "utilisationSchematica", "coherenceLumieres", "roleplayPays", "organics", "surfaceConstruite", "staff"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArchitectureEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArchitectureEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "terraforming": obj.get("terraforming"),
            "coherenceStyle": obj.get("coherenceStyle"),
            "activiteRecente": obj.get("activiteRecente"),
            "blocsCatalogue": obj.get("blocsCatalogue"),
            "trouMissiles": obj.get("trouMissiles"),
            "beauteGenerale": obj.get("beauteGenerale"),
            "habitabiliteMaison": obj.get("habitabiliteMaison"),
            "biomeCoherent": obj.get("biomeCoherent"),
            "batimentsAbandonnes": obj.get("batimentsAbandonnes"),
            "utilisationSchematica": obj.get("utilisationSchematica"),
            "coherenceLumieres": obj.get("coherenceLumieres"),
            "roleplayPays": obj.get("roleplayPays"),
            "organics": obj.get("organics"),
            "surfaceConstruite": obj.get("surfaceConstruite"),
            "staff": obj.get("staff")
        })
        return _obj


