# coding: utf-8

"""
    Yoxo API Server

    API REST exposant diverses données liées aux serveurs de NationsGlory.  ## À propos Cette API centralise et expose différents types de données relatives aux serveurs de NationsGlory : - **Routes `/v2/java/*`** : Données collectées par scraping direct sur les serveurs Java de NationsGlory. Pour cela, le protocole 78 (Minecraft 1.6.4) est pleinement utilisé. - **Autres routes** (à venir) : Données obtenues par d'autres méthodes (API officielles, DynMap, etc.)  ## Authentification L'API utilise le flux OAuth2 Client Credentials. Pour vous authentifier : 1. Obtenez vos identifiants client (client_id et client_secret) depuis le serveur d'authentification de Yoxo 2. Demandez un jeton d'accès : `POST https://auth.yoxo.software/oauth2/token`    ```    grant_type=client_credentials    &client_id=votre_client_id    &client_secret=votre_client_secret    &scope=api_access    ``` 3. Incluez le jeton dans l'en-tête Authorization : `Bearer <token>`  ## Filtrage RSQL Utilisez le paramètre de requête `filter` avec la syntaxe RSQL : - **Opérateurs** : `==`, `!=`, `>`, `>=`, `<`, `<=` - **Logique** : `;` (ET), `,` (OU), `()` pour grouper - **Wildcards** : `*` pour contains/startsWith/endsWith - **Exemples** :   - `b>100000` : niveau global > 100000   - `u==*Romain*` : nom d'utilisateur contenant \"Romain\"   - `b>500000;bP<100` : niveau > 500000 ET position < 100   - `(u==*35*,u==*76*)` : nom contenant \"35\" OU \"76\" 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from yoxo_api_client.models.enterprise_bank import EnterpriseBank
from yoxo_api_client.models.enterprise_permission import EnterprisePermission
from typing import Optional, Set
from typing_extensions import Self

class EnterpriseCasino(BaseModel):
    """
    Entreprise casino
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, description="Type d'entreprise")
    name: Optional[StrictStr] = Field(default=None, description="Nom de l'entreprise")
    age: Optional[StrictInt] = Field(default=None, description="Âge de l'entreprise en jours")
    description: Optional[StrictStr] = Field(default=None, description="Description de l'entreprise")
    services: Optional[StrictStr] = Field(default=None, description="Services proposés")
    owner: Optional[StrictStr] = Field(default=None, description="Propriétaire de l'entreprise")
    flag: Optional[StrictStr] = Field(default=None, description="Drapeau de l'entreprise, sous la forme d'image en Base64")
    cadres: Optional[List[StrictStr]] = Field(default=None, description="Liste des cadres de l'entreprise")
    employees: Optional[List[StrictStr]] = Field(default=None, description="Liste des employés de l'entreprise")
    contracts_done: Optional[StrictInt] = Field(default=None, description="Nombre de contrats réalisés", alias="contractsDone")
    disputes: Optional[StrictInt] = Field(default=None, description="Nombre de litiges")
    contracts_success: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Taux de réussite des contrats (pourcentage)", alias="contractsSuccess")
    turnover: Optional[StrictInt] = Field(default=None, description="Chiffre d'affaires total")
    permissions: Optional[List[EnterprisePermission]] = Field(default=None, description="Permissions de l'entreprise")
    bank: Optional[EnterpriseBank] = None
    history: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, description="Historique des bénéfices du casino par date")
    benef_average: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Bénéfice moyen (par jours)", alias="benefAverage")
    total_play: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Sommes totale jouée", alias="totalPlay")
    win_percent: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Taux de redistribution des gains (en pourcentage)", alias="winPercent")
    total_win: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Somme totale des gains distribuées aux joueurs", alias="totalWin")
    __properties: ClassVar[List[str]] = ["type", "name", "age", "description", "services", "owner", "flag", "cadres", "employees", "contractsDone", "disputes", "contractsSuccess", "turnover", "permissions", "bank", "history", "benefAverage", "totalPlay", "winPercent", "totalWin"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['build', 'engineer', 'terraform', 'journalist', 'casino', 'pvp', 'loan', 'realestate', 'trader', 'bet', 'repair', 'lawyer', 'electric', 'petrol', 'farm']):
            raise ValueError("must be one of enum values ('build', 'engineer', 'terraform', 'journalist', 'casino', 'pvp', 'loan', 'realestate', 'trader', 'bet', 'repair', 'lawyer', 'electric', 'petrol', 'farm')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnterpriseCasino from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in permissions (list)
        _items = []
        if self.permissions:
            for _item_permissions in self.permissions:
                if _item_permissions:
                    _items.append(_item_permissions.to_dict())
            _dict['permissions'] = _items
        # override the default output from pydantic by calling `to_dict()` of bank
        if self.bank:
            _dict['bank'] = self.bank.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnterpriseCasino from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "name": obj.get("name"),
            "age": obj.get("age"),
            "description": obj.get("description"),
            "services": obj.get("services"),
            "owner": obj.get("owner"),
            "flag": obj.get("flag"),
            "cadres": obj.get("cadres"),
            "employees": obj.get("employees"),
            "contractsDone": obj.get("contractsDone"),
            "disputes": obj.get("disputes"),
            "contractsSuccess": obj.get("contractsSuccess"),
            "turnover": obj.get("turnover"),
            "permissions": [EnterprisePermission.from_dict(_item) for _item in obj["permissions"]] if obj.get("permissions") is not None else None,
            "bank": EnterpriseBank.from_dict(obj["bank"]) if obj.get("bank") is not None else None,
            "history": obj.get("history"),
            "benefAverage": obj.get("benefAverage"),
            "totalPlay": obj.get("totalPlay"),
            "winPercent": obj.get("winPercent"),
            "totalWin": obj.get("totalWin")
        })
        return _obj


